### ISSUE TITLE
Errors running situational_awareness or credential modules - greenlet.py

### ISSUE THREAD

**Issue by KMGbully** [byt3bl33d3r/CrackMapExec#109]
Traceback (most recent call last):
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/CrackMapExec/core/connector.py", line 111, in connector
    cmeserver.server.context.localip = local_ip
AttributeError: 'CMEServer' object has no attribute 'server'
<Greenlet at 0x7fb03e0ccb90: connector('192.168.1.124', Namespace(command=None, cred_id=None, depth=10, do, <core.database.CMEDatabase instance at 0x7fb03dffe, <payload_module.CMEModule instance at 0x7fb03dffe6, <core.context.Context instance at 0x7fb03dffe5f0>, <CMEServer(Thread-1, stopped 140394931997584)>)> failed with AttributeError

Traceback (most recent call last):
  File "./crackmapexec.py", line 256, in <module>
    server.shutdown()
  File "/opt/CrackMapExec/core/cmeserver.py", line 67, in shutdown
    while len(self.server.hosts) > 0:
AttributeError: 'CMEServer' object has no attribute 'server'

**Comment by byt3bl33d3r** [comment]
This should be fixed now, let me know otherwise.
