### ISSUE TITLE
Tracebacks when deleting local users

### ISSUE THREAD

**Issue by juushya** [byt3bl33d3r/CrackMapExec#114]
Using the current CME version.

As a Domain Admin, when using CME to delete a local user, the following tracebacks happen:

```
Traceback 1:

05-27-2016 14:51:20 CME          1.2.3.4:445 VICTIM-BOX1        [*] Windows Server 2008 R2 Enterprise 7601 Service Pack 1 (name:VICTIM-BOX1) (domain:DOMAIN)
05-27-2016 14:51:20 CME          1.2.3.4:445 VICTIM-BOX1        [+] DOMAIN\newdomainuser:password (Pwn3d!)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/CME/core/connector.py", line 125, in connector
    output = connection.execute(args.command, get_output=get_output, method=args.exec_method)
  File "/opt/CME/core/connection.py", line 219, in execute
    exec_method = WMIEXEC(self.host, self.username, self.password, self.domain, self.conn, self.hash, self.args.share)
  File "/opt/CME/core/execmethods/wmiexec.py", line 39, in __init__
    iInterface = self.__dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1053, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1711, in RemoteCreateInstance
    self.__portmap.bind(IID_IRemoteSCMActivator)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1012, in bind
    bindResp = MSRPCBindAck(str(resp))
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 748, in __init__
    MSRPCHeader.__init__(self,data,alignment)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 635, in __init__
    Structure.__init__(self,data, alignment)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 82, in __init__
    self.fromString(data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 762, in fromString
    Structure.fromString(self,data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 147, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 302, in unpack
    return self.unpack(two[0],data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 356, in unpack
    return unpack(format, data)[0]
error: ('unpack requires a string argument of length 2', "When unpacking field 'max_tfrag | <H=0 | ''[:2]'")
<Greenlet at 0x3809370: connector('1.2.3.4', Namespace(command='net user newlocaluser /del', cre, <core.database.CMEDatabase instance at 0x387f1b8>, None, None, None)> failed with error

05-27-2016 14:51:20 [*] KTHXBYE!
```

```
Traceback 2:
05-27-2016 14:49:22 CME          2.3.4.5:445 VICTIM-BOX2          [*] Windows Server 2003 R2 3790 Service Pack 2 (name:VICTIM-BOX2) (domain:DOMAIN)
05-27-2016 14:49:22 CME          2.3.4.5:445 VICTIM-BOX2          [+] DOMAIN\newdomainuser:password (Pwn3d!)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/CME/core/connector.py", line 125, in connector
    output = connection.execute(args.command, get_output=get_output, method=args.exec_method)
  File "/opt/CME/core/connection.py", line 219, in execute
    exec_method = WMIEXEC(self.host, self.username, self.password, self.domain, self.conn, self.hash, self.args.share)
  File "/opt/CME/core/execmethods/wmiexec.py", line 39, in __init__
    iInterface = self.__dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1053, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1711, in RemoteCreateInstance
    self.__portmap.bind(IID_IRemoteSCMActivator)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1012, in bind
    bindResp = MSRPCBindAck(str(resp))
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 748, in __init__
    MSRPCHeader.__init__(self,data,alignment)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 635, in __init__
    Structure.__init__(self,data, alignment)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 82, in __init__
    self.fromString(data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 762, in fromString
    Structure.fromString(self,data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 147, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 302, in unpack
    return self.unpack(two[0],data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 356, in unpack
    return unpack(format, data)[0]
error: ('unpack requires a string argument of length 2', "When unpacking field 'max_tfrag | <H=0 | ''[:2]'")
<Greenlet at 0x1d58370: connector('2.3.4.5', Namespace(command='net user newlocaluser /del', cre, <core.database.CMEDatabase instance at 0x1dce1b8>, None, None, None)> failed with error

05-27-2016 14:49:22 [*] KTHXBYE!

```

**Comment by byt3bl33d3r** [comment]
@juushya Command string you ran would help here as well. Cheers

**Comment by juushya** [comment]
Sure.

./crackmapexec.py 1.2.3.4 -d DOMAIN -u domainadmin -p password -x 'net user newlocaluser /del'

**Comment by mpgn** [comment]
Cannot reproduce in v5

![image](https://user-images.githubusercontent.com/5891788/79996510-d758ee80-84b8-11ea-8acc-373d70fcc28c.png)

Feel free to re-open if you still get this error.
