### ISSUE TITLE
Accept Net-Bios names, hostnames, FQDNs as targets

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#13]
Hello @byt3bl33d3r,

Could you adapt the script in order for it to accept valid domain names instead of only IP addresses ?

```
(venvcrackmapexec)root@kali:~/CrackMapExec# python crackmapexec.py -t 2 localhost
Traceback (most recent call last):
  File "crackmapexec.py", line 3129, in <module>
    hosts = IPNetwork(args.target[0])
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 933, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % addr)
netaddr.core.AddrFormatError: invalid IPNetwork localhost

(venvcrackmapexec)root@kali:~/CrackMapExec# python crackmapexec.py -t 2 google.fr
Traceback (most recent call last):
  File "crackmapexec.py", line 3129, in <module>
    hosts = IPNetwork(args.target[0])
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 933, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % addr)
netaddr.core.AddrFormatError: invalid IPNetwork google.fr
```

**Comment by byt3bl33d3r** [comment]
@maaaaz I'm assuming you mean NET-Bios names?  Domain names wouldn't make any sense

**Comment by maaaaz** [comment]
Yes!

**Comment by byt3bl33d3r** [comment]
@maaaaz cool, this should be fairly easy to implement to

**Comment by maaaaz** [comment]
Great, can't wait to test it !
