### ISSUE TITLE
database setup

### ISSUE THREAD

**Issue by 9andrea1** [byt3bl33d3r/CrackMapExec#137]
## Steps to reproduce

MIMIKATZ     192.168.7.82                      [+] Found credentials in Mimikatz output (domain\username:password)

Exception happened during processing of request from ('192.168.7.82', 64044)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/cmeserver.py", line 33, in do_POST
    self.server.module.on_response(self.server.context, self)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/modules/mimikatz.py", line 219, in on_response
    context.db.add_credential(credtype, domain, username, password, hostid)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/database.py", line 30, in add_credential
    cur.execute("INSERT INTO credentials (credtype, domain, username, password, pillagedfrom) VALUES (?,?,?,?,?)", [credtype, domain, username, password, pillaged_from] )
OperationalError: table credentials has no column named pillagedfrom
## Command string used

crackmapexec 192.168.7.0/24 -d test -u test -p password1 -M mimikatz
## OS

Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.6-1kali1 (2016-10-17) x86_64 GNU/Linux
## Detailed issue explanation

Seems to be database setup error; cme installed with both methods, same error.

**Comment by byt3bl33d3r** [comment]
@9andrea1 you seem to be using the bleeding edge version from github, bugs are expected since it is not stable.
I'd suggest using the stable version which you can install by running ```pip install crackmapexec```
Cheers

**Comment by 9andrea1** [comment]
@byt3bl33d3r it was installed running pip, anyway it works properly now in new kali `Linux kali 4.8.0-kali1-amd64 #1 SMP Debian 4.8.5-1kali1 (2016-11-04) x86_64 GNU/Linux`
thanks

**Comment by Open-Sec** [comment]
Just delete the .cme directory from directory where you were running crackmapexec, if you don't need previous info obtained.
