### ISSUE TITLE
Crash on --ntds

### ISSUE THREAD

**Issue by cclements** [byt3bl33d3r/CrackMapExec#143]
Encounter a crash trying to run --ntds, error message: TypeError: NTDS_dump() takes exactly 4 arguments (1 given)

Complete Command output:
```
crackmapexec -u admin -p password -d domain 10.1.1.3 --ntds vss
12-05-2016 12:53:19 CME          10.1.1.2:445 DC1       [*] Windows Server 2003 3790 Service Pack 2 (name:user) (domain:domain)
12-05-2016 12:53:19 CME          10.1.1.2:445 DC1       [+] domain\user:password (Pwn3d!)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 176, in __init__
    getattr(self, k)()
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 39, in _decorator
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 505, in ntds
    return DumpSecrets(self).NTDS_dump()
TypeError: NTDS_dump() takes exactly 4 arguments (1 given)
<Greenlet at 0x7f83db868230: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7f83db0ed9, '10.1.1.3', None, None)> failed with TypeError

```

**Comment by byt3bl33d3r** [comment]
This should have been fixed in v3.1.5 , please re-open the issue if it's not.
Thanks!
