### ISSUE TITLE
OperationalError: table credentials has no column named pillagedfrom

### ISSUE THREAD

**Issue by cclements** [byt3bl33d3r/CrackMapExec#146]
Latest cme bails with the error: "OperationalError: table credentials has no column named pillagedfrom" 

Just looks like the DB doesn't have a column for 'pillagedfrom'

```
root  /usr/share/crackmapexec/cme  crackmapexec 192.168.60.131 -u user -p pass
CME          192.168.60.131:445 user-W7    [*] Windows 6.1 Build 7601 (name:user-W7) (domain:CUST)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 146, in __init__
    self.login()
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 411, in login
    if self.plaintext_login(self.domain, user, password): return
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 253, in plaintext_login
    self.db.add_credential('plaintext', domain, username, password)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/database.py", line 30, in add_credential
    cur.execute("INSERT INTO credentials (credtype, domain, username, password, pillagedfrom) VALUES (?,?,?,?,?)", [credtype, domain, username, password, pillaged_from] )
OperationalError: table credentials has no column named pillagedfrom
Mon Jan  9 15:16:56 2017 <Greenlet at 0x7faeb0915190: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7faeb0935e, '192.168.60.131', None, None)> failed with OperationalError

[*] KTHXBYE!
```

**Comment by byt3bl33d3r** [comment]
@cclements try deleting ~/.cme and try again. You're cme.db file might have the old database format.

**Comment by cclements** [comment]
Sure enough.  That got it.  Thanks!

**Comment by byt3bl33d3r** [comment]
Awesome. Cheers.
