### ISSUE TITLE
cmdb error after upgrading to 4.0.0

### ISSUE THREAD

**Issue by aconite33** [byt3bl33d3r/CrackMapExec#172]
## Steps to reproduce

1. Upgrade to 4.0.0
2. Remove .cme from home directory
3. Scan a network
4. execute cmedb

## Command string used
cmedb

## Platform
Kali Linux x64 (Non-VM)

## Detailed issue explanation
After Upgrading to CME 4.0.0 and running a scan, trying to enter into the cmedb to review results, an error occurs.

## Traceback
Traceback (most recent call last):
  File "/usr/local/bin/cmedb", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'cmedb')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cmedb.py", line 119, in main
    cmedbnav.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 112, in cmdloop
    import readline
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 19, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported

**Comment by byt3bl33d3r** [comment]
So this seems to be an error with Gevent ,which leads me to belive it hasn't been installed correctly.
Did you install CME in a virtualenv?

**Comment by bgx4k3p** [comment]
Getting a similar error here on the latest Kali VM:

```
root@kali:/opt# cmedb
Traceback (most recent call last):
  File "/usr/local/bin/cmedb", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'cmedb')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cmedb.py", line 118, in main
    cmedbnav = CMEDatabaseNavigator(config_path)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cmedb.py", line 31, in __init__
    self.workspace = self.config.get('CME', 'workspace')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'CME'

```

**Comment by void-in** [comment]
Follow the instructions at https://github.com/byt3bl33d3r/CrackMapExec/issues/174 for solution.

**Comment by byt3bl33d3r** [comment]
Cosing since I can't reproduce and no updates.
