### ISSUE TITLE
Unhandled Exception: NetBIOSError

### ISSUE THREAD

**Issue by subfission** [byt3bl33d3r/CrackMapExec#176]
crackmapexec host_list.txt -u superuser -p secretpass

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 71, in __init__
    smb.login('' , '')
  File "/usr/lib/python2.7/dist-packages/impacket/smbconnection.py", line 228, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/usr/lib/python2.7/dist-packages/impacket/smb3.py", line 696, in login
    ans = self.recvSMB(packetID)
  File "/usr/lib/python2.7/dist-packages/impacket/smb3.py", line 356, in recvSMB
    data = self._NetBIOSSession.recv_packet(self._timeout)
  File "/usr/lib/python2.7/dist-packages/impacket/nmb.py", line 855, in recv_packet
    data = self.__read(timeout)
  File "/usr/lib/python2.7/dist-packages/impacket/nmb.py", line 933, in __read
    data = self.read_function(4, timeout)
  File "/usr/lib/python2.7/dist-packages/impacket/nmb.py", line 922, in non_polling_read
    raise NetBIOSError, ( 'Error while reading from remote', ERRCLASS_OS, None)
NetBIOSError: ('Error while reading from remote', 255, None)
<Greenlet at 0x7fe836d7f550: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7fe836d752, '10.0.0.45', None, None)> failed with NetBIOSError

Kali

Windows

**Comment by subfission** [comment]
It appears this exception happens when the host is unreachable.

**Comment by byt3bl33d3r** [comment]
You seem to be using an old version of CME. Try using the one from Github and try again.
Thanks
