### ISSUE TITLE
Pass-Pol Fails when retrieved with hashed credentials

### ISSUE THREAD

**Issue by redteamwynns** [byt3bl33d3r/CrackMapExec#182]
Using a set of hashed credentials in conjunction with --pass-pol makes CME sad. 

cme smb 10.0.5.10 -u idiot -H e51cd6fab1fake7314018bb8eff63806 --pass-pol
```
Traceback (most recent call last):          
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run                                                                                                               result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 173, in __init__
    getattr(self, k)()
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 533, in pass_pol                
    return PassPolDump(self).enum()                                              
  File "/usr/local/lib/python2.7/dist-packages/cme/enum/passpol.py", line 30, in __init__               
    self.lmhash, self.nthash = self.hash.split(':')                                       
ValueError: need more than 1 value to unpack                          
Mon Jun 19 14:09:09 2017 <Greenlet at 0x7fa7e36232d0: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7fa7e33cf5, '10.0.5.10', None, Non
e)> failed with ValueError     
```

Running with cleartext credentials, all else held equal, properly retrieves the password policy. (No account lockouts, minimum 0 pw length, if you were wondering. Because, what else would you use?)

Target OS was Windows 6.1 Build 7601

**Comment by kildonan5** [comment]
I think this error still exist, but in a different place. I typed;
crackmapexec smb 10.11.1.10 -u anotheradmin -H 8846F7EAEE8FB117AD06BDD830B7586C --pass-pol
and get
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 173, in __init__
    getattr(self, k)()
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 533, in pass_pol
    return PassPolDump(self).enum()
  File "/usr/lib/python2.7/dist-packages/cme/enum/passpol.py", line 30, in __init__
    self.lmhash, self.nthash = self.hash.split(':')
ValueError: need more than 1 value to unpack
<Greenlet at 0xb625ec0cL: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0xb629616c>, '10.11.9.145', None, None)> failed with ValueError

Running with a fake LM hash runs without an error, so it seems like the lm:ntlm parsing issue is at play here;
crackmapexec smb 10.11.9.145 -u anotheradmin -H 0:8846F7EAEE8FB117AD06BDD830B7586C --pass-pol
works fine.

**Comment by kildonan5** [comment]
im running version 3.1.5 (which apt-get says is the latest)

**Comment by jeffmcjunkin** [comment]
Confirmed the same thing @kildonan5 mentioned today:
```
sudo cme smb target-hostname -u Administrator -H 31d6cfe0d16ae931b73c59d7e0c089c0 --lusers
CME          target-hostname:445 LAB             [*] Windows 6.3 Build 9600 (name:LAB) (domain:LAB)
CME          target-hostname:445 LAB             [+] LAB\Administrator 31d6cfe0d16ae931b73c59d7e0c089c0 (Pwn3d!)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 173, in __init__
    getattr(self, k)()
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 536, in lusers
    return RPCQUERY(self).enum_lusers()
  File "/usr/local/lib/python2.7/dist-packages/cme/enum/rpcquery.py", line 21, in __init__
    self.lmhash, self.nthash = self.hash.split(':')
ValueError: need more than 1 value to unpack
2018-11-09T23:51:16Z <Greenlet "Greenlet-0" at 0x7f34729eb578: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7f34729d4d, 'target-hostname', None, None)> failed with ValueError
```

I replaced the IP and hash. 

It worked by prefixing `0:` to the NT hash, though:
```
jeff@blue:~$ sudo cme smb target-hostname -u Administrator -H 0:31d6cfe0d16ae931b73c59d7e0c089c0 --lusers
CME          target-hostname:445 LAB             [*] Windows 6.3 Build 9600 (name:LAB) (domain:LAB)
CME          target-hostname:445 LAB             [+] LAB\Administrator 0:31d6cfe0d16ae931b73c59d7e0c089c0 (Pwn3d!)
CME          target-hostname:445 LAB             [+] Enumerating logged on users
CME          target-hostname:445 LAB             Username: LAB\Administrator LogonServer: LAB
```
