### ISSUE TITLE
Impacket Error Handling Suggestion

### ISSUE THREAD

**Issue by redteamwynns** [byt3bl33d3r/CrackMapExec#188]
ME AGAIN

Running cme against a system with a non-standard service (routersetup Nortel/D-Link router instant setup) running on 445 yields an impacket error as it attempts to determine the smb security mode. On this particular device, netbios-ssn is running on 139, and also returns the same debug output. 

cme 172.24.166.151

# CME verbose output
```
`{'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': None, 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': [], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': [], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['172.24.166.151'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 62, in __init__
    smb = SMBConnection(self.host, self.host, None, self.args.smb_port)
  File "/usr/lib/python2.7/dist-packages/impacket/smbconnection.py", line 63, in __init__
    self.negotiateSession(preferredDialect)
  File "/usr/lib/python2.7/dist-packages/impacket/smbconnection.py", line 92, in negotiateSession
    negPacket=packet)
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 2411, in __init__
    self.neg_session(negPacket = negPacket)
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 2609, in neg_session
    return parsePacket( NewSMBPacket( data = negPacket))
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 2562, in parsePacket
    self._dialects_parameters = SMBNTLMDialect_Parameters(sessionResponse['Parameters'])
  File "/usr/lib/python2.7/dist-packages/impacket/structure.py", line 82, in __init__
    self.fromString(data)
  File "/usr/lib/python2.7/dist-packages/impacket/structure.py", line 147, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/lib/python2.7/dist-packages/impacket/structure.py", line 356, in unpack
    return unpack(format, data)[0]
error: ('unpack requires a string argument of length 1', "When unpacking field 'SecurityMode | <B | ''[:1]'")
Thu Jul  6 09:16:07 2017 <Greenlet at 0x7fa4069fb0f0: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7fa4069f3b, '172.24.166.151', None, None)> failed with error`
```
# OS: linux or something

# Target system was a Kyocera TASKalfa copier

# Detailed issue explanation: shit's broken

**Comment by byt3bl33d3r** [comment]
@redteamwynns hmmmm what cme version were you using? this looks like 3.x

**Comment by byt3bl33d3r** [comment]
Closing since this was happening with 3.x
