### ISSUE TITLE
Error while launching Empire with CrackMapExec

### ISSUE THREAD

**Issue by str4n63r** [byt3bl33d3r/CrackMapExec#192]
## CME verbose output (using the --verbose flag)
**Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/crackmapexec.py", line 151, in main
    module = loader.init_module(props['path'])
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/loaders/module_loader.py", line 96, in init_module
    module.options(context, module_options)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/modules/empire_exec.py", line 50, in options
    self.empire_launcher = r.json()['multi/launcher']['Output']
KeyError: 'multi/launcher'**

## Detailed issue explanation -- Received above error while launching **empire_exec** module from CME

Help appreciated. Thanks in advance.

**Comment by byt3bl33d3r** [comment]
@str4n63r what empire version are you using?

**Comment by str4n63r** [comment]
@byt3bl33d3r Latest pull from Github

**Comment by schniggie** [comment]
Having the same issue:

`sudo crackmapexec smb IPs.txt -u User -H 12345678902bbbe760ea1f1234567890 -M empire_exec -o LISTENER=CME`

Result:
```
Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==3.1.5', 'console_scripts', 'crackmapexec')()
  File "/usr/lib/python2.7/dist-packages/cme/crackmapexec.py", line 219, in main
    module, context, server = loader.init_module(modules[m]['path'])
  File "/usr/lib/python2.7/dist-packages/cme/moduleloader.py", line 82, in init_module
    module.options(context, module_options)
  File "/usr/lib/python2.7/dist-packages/cme/modules/empire_exec.py", line 46, in options
    self.empire_launcher = r.json()['launcher']['Output']
KeyError: 'launcher'
```

CME is from current Kali-rolling and Empire is from Github today.

**Comment by dinvisible1** [comment]
same issue with out the Empire part, 

root@kali:/opt/CrackMapExec# cme
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'cme')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/crackmapexec.py", line 33, in main
    args = gen_cli_args()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cli.py", line 67, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/loaders/protocol_loader.py", line 12, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/protocols/smb.py", line 30, in <module>
    from pywerview.cli.helpers import *
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.2-py2.7-linux-x86_64.egg/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named pywerview.cli.helpers

CME is from current Kali-rolling

**Comment by swarleysez** [comment]
Any update to this?  Using CME 3.1.5 from Kali repo and Empire 2.0.  Using the absolute path (/usr/bin/crackmapexec) doesn't work for me.

**Comment by SDGoodwin** [comment]
Having the same issue:

CME
Version: 3.1.5
Codename: 'Smidge'

Rolling Kali
confirmed current 30NOV17 (apt-get update, apt-get upgrade, apt-get dist-upgrade)

**Comment by lan1ak3a-2** [comment]
Same Here. 
Mac High Sierra 10.13.3
Version 3.1.5
'Smidge'
lan1ak3as-mbp:Applications ****$ sudo cme smb [IP] -u [UNAME] -p [PW] -M empire_exec -o LISTENER=empire
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    sys.exit(main())
  File "/Users/*/Library/Python/2.7/lib/python/site-packages/cme/crackmapexec.py", line 219, in main
    module, context, server = loader.init_module(modules[m]['path'])
  File "/Users/*/Library/Python/2.7/lib/python/site-packages/cme/moduleloader.py", line 82, in init_module
    module.options(context, module_options)
  File "/Users/*/Library/Python/2.7/lib/python/site-packages/cme/modules/empire_exec.py", line 46, in options
    self.empire_launcher = r.json()['launcher']['Output']
KeyError: 'launcher'

**Comment by byt3bl33d3r** [comment]
I'll take a look at this now. This is probably happening cause Empire changed it's API again.

**Comment by kylesmithit** [comment]
Thank you @byt3bl33d3r for your dedication in keeping up with the API!

**Comment by n3gz404** [comment]
Hi, same exact issue as all those above. Still no fix?

**Comment by hausec** [comment]
Also having this issue. Running it from /usr/bin doesn't work either.

**Comment by holyshift** [comment]
in Kali for KeyError: 'launcher', i had the same issue here is what i did :
1 - open /usr/lib/python2.7/dist-packages/cme/modules/empire_exec.py
2- in ligne 44  replace "launcher" with an empire stager like "windows/dll" for exemple
3- in line 46 : replace "self.empire_launcher = r.json()['launcher']['Output']" ===> self.empire_launcher = r.json()['windows/dll']['Output']
try launching CME now, good luck

**Comment by hausec** [comment]
> in Kali for KeyError: 'launcher', i had the same issue here is what i did :
> 1 - open /usr/lib/python2.7/dist-packages/cme/modules/empire_exec.py
> 2- in ligne 44 replace "launcher" with an empire stager like "windows/dll" for exemple
> 3- in line 46 : replace "self.empire_launcher = r.json()['launcher']['Output']" ===> self.empire_launcher = r.json()['windows/dll']['Output']
> try launching CME now, good luck

That worked. Thanks!

**Comment by mpgn** [comment]
Some have tested this with this project ? https://github.com/BC-SECURITY/Empire/ 
Do we need to apply a fix or a close this issue ?

**Comment by lolcatlolcat** [comment]
> Someone have tested with this project ? https://github.com/BC-SECURITY/Empire/
![image](https://user-images.githubusercontent.com/25574768/80815046-f8959b00-8b9a-11ea-8ab4-951079cc5a21.png)
![image](https://user-images.githubusercontent.com/25574768/80815094-04815d00-8b9b-11ea-934f-748611af640b.png)
Tested it this morning against a fresh-install of Server2016 with the latest powershell-empire from BC-Security. Worked fine for me.

**Comment by mpgn** [comment]
Closing, follow issue (empire and metasploit module ) #357
