### ISSUE TITLE
Fix ImportError: No module named pywerview.cli.helpers

### ISSUE THREAD

**Issue by sheimo** [byt3bl33d3r/CrackMapExec#199]
## Steps to reproduce

1. apt update && apt install crackmapexec
2. cme 

[root:/opt]# cme
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'cme')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/crackmapexec.py", line 33, in main
    args = gen_cli_args()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cli.py", line 67, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/loaders/protocol_loader.py", line 12, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/protocols/smb.py", line 30, in <module>
    from pywerview.cli.helpers import *
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named pywerview.cli.helpers

DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2017.1"
VERSION_ID="2017.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"

Fix:
pip install pywerview

**Comment by Vancer** [comment]
+1 Fix works!

**Comment by byt3bl33d3r** [comment]
This seems to be a problem with the Kali package, you might want to bring this up in the Kali bug tracker.
Thanks
