### ISSUE TITLE
No valid Connections Error help me out

### ISSUE THREAD

**Issue by BlackRat2** [byt3bl33d3r/CrackMapExec#209]
Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 9, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/crackmapexec.py", line 33, in main
    args = gen_cli_args()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cli.py", line 67, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/loaders/protocol_loader.py", line 12, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/protocols/ssh.py", line 5, in <module>
    from paramiko.ssh_exception import AuthenticationException, NoValidConnectionsError, SSHException
ImportError: cannot import name NoValidConnectionsError

**Comment by BlackRat2** [comment]
[Screencast_10-06-2017_07:13:49 AM.webm.zip](https://github.com/byt3bl33d3r/CrackMapExec/files/1361313/Screencast_10-06-2017_07.13.49.AM.webm.zip)

**Comment by byt3bl33d3r** [comment]
Gonna need a lot more info. fill out the Issue template and re-submit.

**Comment by soltan1991github** [comment]
1- download crackmapexec
git clone https://github.com/Porchetta-Industries/CrackMapExec.git 
2-go to the folder 'CrackMapExec' and execute command 
pip3 install -r requirements.txt 
fixed ;)
