### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by leebaird** [byt3bl33d3r/CrackMapExec#217]
## Steps to reproduce

root@kali:/opt/CrackMapExec# cme
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'cme')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'

## CME Version (cme --version)
root@kali:/opt/CrackMapExec# cme --version
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'cme')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'

## OS
latest Kali

**Comment by h3xg4m3s** [comment]
Be sure to clone the repo with the recursive switch.
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec

**Comment by twsjozef** [comment]
Any Solution ?

**Comment by secwatch** [comment]
apt install -y libssl-dev libffi-dev python-dev build-essential
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec
pip install -r requirements.txt
python setup.py install

**Comment by fhidalgo** [comment]
There should be a build folder inside your cloned repository after the setup. It contains a cme folder with the thirdparty folder missing. Copying it to were is supposed to be in the error worked for me.

**Comment by dgrivera** [comment]
@fhidalgo thank you for the help! simple but gold!

**Comment by dtrybalski** [comment]
any idea about the missing winrm.py module for python2.7?

**Comment by mpgn** [comment]
- Use the python3 version of crackmapexec : 

```
git clone --recursive https://github.com/mpgn/CrackMapExec && cd CrackMapExec
git checkout python3
git submodule update --recursive
python3 setup.py install
cme
```

- or from kali : `apt install crackmapexec`

**Comment by pshuker** [comment]
> There should be a build folder inside your cloned repository after the setup. It contains a cme folder with the thirdparty folder missing. Copying it to were is supposed to be in the error worked for me.

Absolute legend mate

**Comment by sergioab7** [comment]
**thanks for help**

**Comment by DOP7** [comment]
To install Crackmapexec:
sudo git clone https://github.com/byt3bl33d3r/CrackMapExec
cd crackMapExec
pip3 install -r requirements.txt
sudo apt install crackmapexec -y


Note: You can remove the folder crackmapexec after running requirements.txt(this is important before you install crackmapexec)
This will not get you any above traceback errors

**Comment by ssitaraman8084** [comment]
crackmapexec 5.4.0 version throws an error for smb bruteforcing.

 File "/usr/bin/crackmapexec", line 8, in <module>                                                                                                                                                               
    sys.exit(main())                                                                                                                                                                                              
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 165, in main                                                                                                                                    
    target_file_type = identify_target_file(target)                                                      
  File "/usr/lib/python3/dist-packages/cme/helpers/misc.py", line 12, in identify_target_file
    with open(target_file, 'r') as target_file_handle:
IsADirectoryError: [Errno 21] Is a directory: '10.10.10.1x'

try to use /32 for the ip address

**Comment by allyoung1010** [comment]
> crackmapexec 5.4.0 version throws an error for smb bruteforcing.
> 
> File "/usr/bin/crackmapexec", line 8, in sys.exit(main()) File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 165, in main target_file_type = identify_target_file(target) File "/usr/lib/python3/dist-packages/cme/helpers/misc.py", line 12, in identify_target_file with open(target_file, 'r') as target_file_handle: IsADirectoryError: [Errno 21] Is a directory: '10.10.10.1x'
> 
> try to use /32 for the ip address

it works ,thanks~
