### ISSUE TITLE
crash on start. odd python error with import

### ISSUE THREAD

**Issue by GIJack** [byt3bl33d3r/CrackMapExec#241]
## Steps to reproduce

1. install crackmapexec on Arch via AUR: https://aur.archlinux.org/packages/crackmapexec/
2. run crackmapexe on the command line

## Command string used
$ crackmapexec

## CME verbose output (using the --verbose flag)
$ crackmapexec 
Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python' distribution was not found and is required by crackmapexec

## OS
$ uname -a
Linux BOX 4.15.13-1-ARCH #1 SMP PREEMPT Sun Mar 25 11:27:57 UTC 2018 x86_64 GNU/Linux
$ pacman -Q python2
python2 2.7.14-2
$ pacman -Q python2-msgpack 
python2-msgpack 0.5.6-1

## Target OS
same

## Detailed issue explanation
python2 error, program crashes on start, appears to be an issue with python. After careful testing,

__requires__ = 'crackmapexec==3.1.5'

causes

from pkg_resources import load_entry_point

to fail with above error. The below line otherwise works fine.

**Comment by byt3bl33d3r** [comment]
I didn't even know there was a CME AUR package. This seems to be a packaging issue and not a bug with CME itself. You should probably post this as a comment on the AUR page to see if the package maintainer can fix it.

**Comment by GIJack** [comment]
Sure, that may or may not be me if the person does not respond. I checked your page. do you have manual install instructions we can use for the AUR package?

**Comment by felbutss** [comment]
here is the fix 

pip install --force "Sphinx < 3.141.0"


if that doesnt work then do

cd CrackMapExec/
pipenv shell
pip install --force "Sphinx < 3.141.0"
