### ISSUE TITLE
Can't install CME 4.X

### ISSUE THREAD

**Issue by CaledoniaProject** [byt3bl33d3r/CrackMapExec#246]
## Steps to reproduce

1. Download master branch aka master.zip and extract it
2. Install dependencies via pip install -r requirements.txt
3. Install CME4 with python setup.py install

## Command string used

When I launch it, I got errors like this, the `thirdparty` folder is missing.

```
Traceback (most recent call last):
  File "/usr/local/python2.7/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/local/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/local/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/local/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/python2.7/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/usr/local/python2.7/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'
```

**Comment by CaledoniaProject** [comment]
BTW, are you planning to upload CME 4.X to pip store recently?

**Comment by binkboyd** [comment]
When downloading as a .zip it doesn't seem like github includes the submodules of the repository. Try cloning the repo using the --recursive option as shown on the wiki install page: https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation

**Comment by rets34** [comment]
I get the same issue even after using pipenv to install

**Comment by byt3bl33d3r** [comment]
Your running CME on windows which isn't supported.

**Comment by omergafni** [comment]
Actually,
there is a little change that you have to make in order to get CME work on
windows.

I manage to figure it out once I made this change inside the 'first_run.py'
file:
change the '\tmp' path in line 11 to something that exists over windows
machine.

hope that you will like it :-)

-Omer
