### ISSUE TITLE
Error with RDP module

### ISSUE THREAD

**Issue by cclements** [byt3bl33d3r/CrackMapExec#251]
Hello, ran into this error when trying to run the rdp module:

```
cme smb 192.168.0.100 -u USER -p 'PASSWORD' -M rdp -o enable --obfs
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-TyYiRZur/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'cme')()
  File "/root/.local/share/virtualenvs/CrackMapExec-TyYiRZur/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/crackmapexec.py", line 162, in main
    module = loader.init_module(props['path'])
  File "/root/.local/share/virtualenvs/CrackMapExec-TyYiRZur/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/loaders/module_loader.py", line 93, in init_module
    key, value = option.split('=', 1)
ValueError: need more than 1 value to unpack
```

**Comment by cclements** [comment]
This was my fault.  I had the syntax wrong.  Correct syntax is:

cme smb 192.168.0.100 -u USER -p 'PASSWORD' -M rdp -o ACTION='enable'
