### ISSUE TITLE
Bind context 1 rejected: provider_rejection; abstract_syntax_not_supported (this usually means the interface isn't listening on the given endpoint)

### ISSUE THREAD

**Issue by fede333lago** [byt3bl33d3r/CrackMapExec#252]
## Steps to reproduce

1. Installed Impacket from github repo from scratch 
2. Installed cme bleeding edge on debian and run it inside pipenv.

## Command string used
```
crackmapexec smb 10.0.0.5 -u freddy -p test -x ipconfig

## CME verbose output (using the --verbose flag)
crackmapexec --verbose smb 10.0.0.5 -u freddy -p test -x ipconfig                          
DEBUG Passed args:
{'clear_obfscripts': False,
 'content': False,
 'cred_id': [],
 'darrell': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': None,
 'execute': 'ipconfig',
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': None,
 'module_options': [],
 'no_output': False,
 'ntds': None,
 'obfs': False,
 'only_files': False,
 'pass_pol': False,
 'password': ['test'],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'ps_execute': None,
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'server': 'https',
 'server_host': '0.0.0.0',
 'server_port': None,
 'sessions': False,
 'share': 'C$',
 'shares': False,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['10.0.0.5'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': ['freddy'],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}
SMB         10.0.0.5     445    DJ               [*] Windows 5.0 x32 (name:DJ) (domain:DJ) (signing:False) (SMBv1:True)
DEBUG add_credential(credtype=plaintext, domain=DJ, username=freddy, password=test, groupid=None, pillaged_from=None) => None
SMB         10.0.0.5     445    DJ               [+] DJ\freddy:test (Pwn3d!)
DEBUG Calling execute()
DEBUG Starting SMB server
DEBUG Config file parsed
DEBUG Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
DEBUG Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
DEBUG Config file parsed
DEBUG Config file parsed
DEBUG Config file parsed
DEBUG Error executing command via wmiexec, traceback:
DEBUG Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 391, in execute
    exec_method = WMIEXEC(self.host, self.smb_share_name, self.username, self.password, self.domain, self.conn, self.hash, self.args.share)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/wmiexec.py", line 40, in __init__
    iInterface = self.__dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/dcerpc/v5/dcomrt.py", line 1056, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/dcerpc/v5/dcomrt.py", line 1876, in RemoteCreateInstance
    if strBindings[0] == '\x00' and strBindings[1] == '\x00':
IndexError: string index out of range

DEBUG Error executing command via mmcexec, traceback:
DEBUG Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 401, in execute
    exec_method = MMCEXEC(self.host, self.smb_share_name, self.username, self.password, self.domain, self.conn, self.hash)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/mmcexec.py", line 92, in __init__
    self.exit()
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/mmcexec.py", line 129, in exit
    self.__quit[0].Invoke(self.__quit[1], 0x409, DISPATCH_METHOD, dispParams,
TypeError: 'NoneType' object has no attribute '__getitem__'

DEBUG Executed command via atexec
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 110, in __init__
    connection.__init__(self, args, db, host)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 41, in __init__
    self.proto_flow()
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 77, in proto_flow
    self.call_cmd_args()
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 84, in call_cmd_args
    getattr(self, k)()
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 17, in _decorator
    return func(self, *args, **kwargs)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 82, in _decorator
    output = func(self, *args, **kwargs)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 431, in execute
    output = u'{}'.format(exec_method.execute(payload, get_output).strip().decode('utf-8',errors='replace'))
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/atexec.py", line 42, in execute
    self.execute_handler(command)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/atexec.py", line 53, in execute_handler
    self.doStuff(data)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/atexec.py", line 125, in doStuff
    dce.bind(tsch.MSRPC_UUID_TSCHS)
  File "/root/.local/share/virtualenvs/CrackMapExec-NGU82JU9/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/dcerpc/v5/rpcrt.py", line 1045, in bind
    raise DCERPCException(msg)
DCERPCException: Bind context 1 rejected: provider_rejection; abstract_syntax_not_supported (this usually means the interface isn't listening on the given endpoint)
Thu Jun  7 04:53:21 2018 <Greenlet at 0x7fba703c6190: smb(Namespace(clear_obfscripts=False, content=False, c, <protocol.database instance at 0x7fba73eeecb0>, '10.0.0.5')> failed with DCERPCException
```

## CME Version (cme --version)
4.0.1dev - Bug Pr0n

## OS
Debian unstable

## Target OS
Windows Server 2000

## Detailed issue explanation
Hey! I'm currently working on a windows server 2000 and when I try to run any command on the machine (or also with the mimikatz module) I always get that error message. I tried reinstalling cme and impacket from scratch but no difference.

**Comment by kildonan5** [comment]
also seeing this. did you find a fix?

**Comment by flagod** [comment]
No, sorry. It happened with only one host though, so I'm suspecting it's related to a specific smb version.

**Comment by byt3bl33d3r** [comment]
> ```SMB         10.0.0.5     445    DJ               [*] Windows 5.0 x32 (name:DJ) (domain:DJ) (signing:False) (SMBv1:True)```

Nothing should need to be added. We're you using CME in a time bubble?
