### ISSUE TITLE
NameError: global name 'getuser' is not defined

### ISSUE THREAD

**Issue by dmknght** [byt3bl33d3r/CrackMapExec#258]
## Steps to reproduce

Hi! I've got this error. I think it is programing syntax error. Please check details bellow. Thanks!

## Command string used
`cme smb <target_ip_addr> -u "" -p "" -M mimikatz`
## CME verbose output (using the --verbose flag)
```
DEBUG                                          {'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': 'mimikatz', 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': [''], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': [''], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['smb', '<target_ip_addr>'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cme/crackmapexec.py", line 210, in main
    logger.error("I'm sorry {}, I'm afraid I can't let you do that (cause I need root)".format(getuser()))
NameError: global name 'getuser' is not defined
```
## CME Version (cme --version)
3.1.5 (installed using pip)
## OS
Parrot Security OS 4.1
## Target OS
Windows 6.1 Build 0
## Detailed issue explanation

**Comment by byt3bl33d3r** [comment]
This should be fixed in the version on Github. Closing
