### ISSUE TITLE
WINDOWS ERROR LAUNCH :!\

### ISSUE THREAD

**Issue by Netw0rkLan** [byt3bl33d3r/CrackMapExec#261]
## Steps to reproduce

1. ...
2. ...

## Command string used
python cme.py

## CME verbose output (using the --verbose flag)
```

C:\Palma\CMS\cme>python crackmapexec.py
Traceback (most recent call last):
  File "crackmapexec.py", line 5, in <module>
    from cme.logger import setup_logger, setup_debug_logger, CMEAdapter
  File "C:\Python27\lib\site-packages\crackmapexec-4.0.1.dev0-py2.7.egg\cme\__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
WindowsError: [Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable: 'C:\\Python27\\lib\\site-packages\\crackmapexec-4.0.1.dev0-py2.7.egg\\cme\\thirdparty/*.*'
```

## CME Version (cme --version)
4.0
## OS
WINDOWS 10

**Comment by byt3bl33d3r** [comment]
CME doesn't support windows. Closing.
