### ISSUE TITLE
cme smb --flag causing crash

### ISSUE THREAD

**Issue by byinarie** [byt3bl33d3r/CrackMapExec#273]
## Steps to reproduce

1. crackmapexec smb --sessions host
or
2. crackmapexec smb --shares host

## CME verbose output (using the --verbose flag)
crackmapexec --verbose smb --sessions 10.10.10.100 
DEBUG Passed args:
{'clear_obfscripts': False,
 'content': False,
 'continue_on_success': False,
 'cred_id': [],
 'darrell': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': None,
 'execute': None,
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': None,
 'module_options': [],
 'no_output': False,
 'ntds': None,
 'obfs': False,
 'only_files': False,
 'pass_pol': False,
 'password': [],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'ps_execute': None,
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'server': 'https',
 'server_host': '0.0.0.0',
 'server_port': None,
 'sessions': True,
 'share': 'C$',
 'shares': False,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['10.10.10.100'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': [],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}
DEBUG SMBv1 might be disabled on 10.10.10.100
DEBUG SMBv1 might be disabled on 10.10.10.100
SMB         10.10.10.100    445    DC               [*] Windows 6.1 Build 7601 x64 (name:DC) (domain:ACTIVE) (signing:True) (SMBv1:False)
DEBUG Calling sessions()
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 110, in __init__
    connection.__init__(self, args, db, host)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 41, in __init__
    self.proto_flow()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 77, in proto_flow
    self.call_cmd_args()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 84, in call_cmd_args
    getattr(self, k)()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 510, in sessions
    sessions = get_netsession(self.host, self.domain, self.username, self.password, self.lmhash, self.nthash)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/pywerview/pywerview/cli/helpers.py", line 140, in get_netsession
    return requester.get_netsession()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/pywerview/pywerview/requester.py", line 228, in wrapper
    instance._create_rpc_connection(pipe=pipe)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/pywerview/pywerview/requester.py", line 200, in _create_rpc_connection
    dce.connect()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/dcerpc/v5/rpcrt.py", line 801, in connect
    return self._transport.connect()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/dcerpc/v5/transport.py", line 388, in connect
    self.__smb_connection.login(self._username, self._password, self._domain, self._lmhash, self._nthash)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/smbconnection.py", line 263, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/smb3.py", line 791, in login
    type3, exportedSessionKey = ntlm.getNTLMSSPType3(auth, respToken['ResponseToken'], user, password, domain, lmhash, nthash)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/ntlm.py", line 603, in getNTLMSSPType3
    user = user.decode(encoding)
AttributeError: 'NoneType' object has no attribute 'decode'
2018-11-03T05:15:32Z <Greenlet "Greenlet-0" at 0x7f1a8478e680: smb(Namespace(clear_obfscripts=False, content=False, c, <protocol.database instance at 0x7f1a84f35b90>, '10.10.10.100')> failed with AttributeError

## CME Version (cme --version)
crackmapexec -v
4.0.1dev - Bug Pr0n

## Kali Rolling 
##Host is am running cme against is a windows server 2012 DC

**Comment by awsmhacks** [comment]
Try 
`crackmapexec smb 10.10.10.100 -u UserNAme -p 'PASSWORDHERE' --sessions`
CME requires (currently) switches/option/params to be in a certain order. --sessions cant come before the host and requires a user and password. Check the https://github.com/byt3bl33d3r/CrackMapExec/wiki/SMB-Command-Reference for help and examples

**Comment by byinarie** [comment]
> 
> 
> Try
> `crackmapexec smb 10.10.10.100 -u UserNAme -p 'PASSWORDHERE' --sessions`
> CME requires (currently) switches/option/params to be in a certain order. --sessions cant come before the host and requires a user and password. Check the https://github.com/byt3bl33d3r/CrackMapExec/wiki/SMB-Command-Reference for help and examples

That worked. I wasn't using the -p or -u flags and was playing a CTF at like 4am. Guess lack of sleep got the best of me lol. Thanks for the help. This can be closed.
