### ISSUE TITLE
kali linux: ValueError: Not a valid python version: <LegacyVersion('2.7.15+')>

### ISSUE THREAD

**Issue by hktalent** [byt3bl33d3r/CrackMapExec#278]
```
pipenv install
kali linux: ValueError: Not a valid python version: <LegacyVersion('2.7.15+')>
```
or 

```
apt install crackmapexec
#crackmapexec 192.168.0.1/16 -d CSCOU -u jarrieta -p nastyCutt3r
Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/**thirdparty**'
```
```
#ls /usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/
cli.py   cmedb.py   connection.py   context.py   crackmapexec.py   data          first_run.pyc  __init__.py   loaders    logger.pyc  msfrpc.py   parsers    servers
cli.pyc  cmedb.pyc  connection.pyc  context.pyc  crackmapexec.pyc  first_run.py  helpers        __init__.pyc  logger.py  modules     msfrpc.pyc  protocols
```

**Comment by byt3bl33d3r** [comment]
brah, the issue template is there for a reason...
What OS are you using ? Gonna need a lot more info. *Please* fill out the issue template.

**Comment by byt3bl33d3r** [comment]
Seems like Kali, you're going to have to file a bug report on kali's bugtracker (https://bugs.kali.org/main_page.php) as this seems to be a packaging issue.
