### ISSUE TITLE
--obfs get error

### ISSUE THREAD

**Issue by Anton19780301** [byt3bl33d3r/CrackMapExec#312]
## Steps to reproduce

1. ...
2. ...

## Command string used
crackmapexec smb 10.241.0.0/24 -u Администратор -p MyPassword --local-auth  -M tokens --obfs
## CME verbose output (using the --verbose flag)

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'

## CME Version (cme --version)

(CrackMapExec) root@kali:~# crackmapexec -version
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/local/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'

## OS
last Kali 
## Target OS
Windows 7

**Comment by Anton19780301** [comment]
I try do this

apt install -y libssl-dev libffi-dev python-dev build-essential 
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec 
cd CrackMapExec 
pip install -r requirements.txt 
python setup.py install

Bat after 

(CrackMapExec) root@kali:~/CrackMapExec# python setup.py install
bash: /root/.local/share/virtualenvs/CrackMapExec-W8h2f6uM/bin/python: Нет такого файла или каталога
(it meen - no file or catalog)

**Comment by Anton19780301** [comment]
the second problem was solved by reinstalling
apt-get install crackmapexec

but --obfs does not work as before

crackmapexec 10.241.0.158 -u Администратор -p MyPassword --local-auth  -M mimikatz -o COMMAND='sekurlsa::logonpasswords' -obfs
Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==3.1.5', 'console_scripts', 'crackmapexec')()
  File "/usr/lib/python2.7/dist-packages/cme/crackmapexec.py", line 219, in main
    module, context, server = loader.init_module(modules[m]['path'])
  File "/usr/lib/python2.7/dist-packages/cme/moduleloader.py", line 79, in init_module
    key, value = option.split('=', 1)
ValueError: need more than 1 value to unpack

maybe you need to do something with my python?
Has anyone come across this?

**Comment by byt3bl33d3r** [comment]
This seems like some sort of packaging error/conflict. You should file a bug with the Kali Linux bug tracker.
