### ISSUE TITLE
HTTP Issue

### ISSUE THREAD

**Issue by LarryCheech** [byt3bl33d3r/CrackMapExec#316]
Im having an issue running CME with the http option. I have followed the install instructions to replace phantomjs but still have this issue
`Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/http.py", line 86, in __init__
    self.proto_flow()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 69, in proto_flow
    if self.create_conn_obj():
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/http.py", line 125, in create_conn_obj
    service_log_path=os.path.expanduser('~/.cme/logs/ghostdriver.log'), desired_capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/splinter/browser.py", line 63, in Browser
    raise DriverNotFoundError("No driver for %s" % driver_name)
DriverNotFoundError: No driver for phantomjs
2019-09-12T15:47:53Z <Greenlet at 0x7f69c9a6a5a0: single_connection(<protocol.http object at 0x7f69e051e750>, 'http', 8080)> failed with DriverNotFoundError
`

**Comment by mpgn** [comment]
Hello,

New version of CME, try with the new version. Feel free to re-open if the error is still present :)
```
apt-get install -y libssl-dev libffi-dev python-dev build-essential
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec
python3 setup.py install
```
