### ISSUE TITLE
installation error while installing CME on Kali by "apt-get install"

### ISSUE THREAD

**Issue by UrfinJuice11** [byt3bl33d3r/CrackMapExec#326]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (crackmapexec 4.0.1.dev0 (/usr/local/lib/python3.7/dist-packages/crackmapexec-4.0.1.dev0-py3.7.egg), Requirement.parse('crackmapexec==3.1.5'))

During handling of the above exception, another exception occurred:

installing CME on Kali by "apt-get install":

Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'crackmapexec==3.1.5' distribution was not found and is required by the application

IF install "pip install crackmapexec" - it installs the 3.1.4 version. "pip install crackmapexec==3.1.5" can not find a package

**Comment by vshah1016** [comment]
you figure it out?

**Comment by mpgn** [comment]
Hello,

Try this

```
apt-get install -y libssl-dev libffi-dev python-dev build-essential
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec
python3 setup.py install
````

**Comment by vshah1016** [comment]
i was able to fix it by moving a folder called thirdparty to where it need to be and doin ga pip3 install of impacket

**Comment by mpgn** [comment]
Nice 👍 i'm closing
