### ISSUE TITLE
MSSQL: struct.error when login

### ISSUE THREAD

**Issue by mpgn** [byt3bl33d3r/CrackMapExec#364]
_Originally posted by @0xe7 in https://github.com/byt3bl33d3r/CrackMapExec/issues/363#issuecomment-622513929_
```
» ./cme mssql 192.168.74.53 -a normal --local-auth -u sa -p /tmp/s
MSSQL       192.168.74.53   1433   None             [*] MSSQL DB Instances: 1
MSSQL       192.168.74.53   1433   None             Instance 0
MSSQL       192.168.74.53   1433   None             ServerName:OTHERSPN
MSSQL       192.168.74.53   1433   None             InstanceName:MSSQLSERVER
MSSQL       192.168.74.53   1433   None             IsClustered:No
MSSQL       192.168.74.53   1433   None             Version:12.0.5000.0
MSSQL       192.168.74.53   1433   None             tcp:1433
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/cme/protocols/mssql.py", line 23, in __init__
    connection.__init__(self, args, db, host)
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/cme/connection.py", line 42, in __init__
    self.proto_flow()
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/cme/protocols/mssql.py", line 56, in proto_flow
    self.login()
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/cme/connection.py", line 239, in login
    if self.plaintext_login(self.domain, user, f_pass.strip()): return True
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/cme/protocols/mssql.py", line 169, in plaintext_login
    res = self.conn.login(None, username, password, domain, None, self.args.auth_type == 'windows')
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/impacket/tds.py", line 905, in login
    resp = self.preLogin()
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/impacket/tds.py", line 520, in preLogin
    tds = self.recvTDS()
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/impacket/tds.py", line 606, in recvTDS
    packet = TDSPacket(self.socketRecv(packetSize))
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/root/.shiv/cme_a9c70d43502efcc2838d1a6c9a5f2db93713cfa654b2df7218d6d3d121d46255/site-packages/impacket/structure.py", line 382, in unpack
    return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'Type | <B | b''[:1]'")
2020-05-01T18:48:04Z <Greenlet at 0x7ff01be067b0: mssql(Namespace(auth_type='normal', clear_obfscripts=Fal, <protocol.database object at 0x7ff01bccbeb0>, '192.168.74.53')> failed with error
```

**Comment by mpgn** [comment]
Tell me if that fix the problem :)

**Comment by 0xe7** [comment]
It stopped the exception, but the login isn't working, the correct password is Somepass4 but it looks like it's trying a blank password each time:

```
(CrackMapExec-VZqQw9ZN) /tmp/CrackMapExec
2020-05-01 22:23:39 192.168.0.102 192.168.74.51
» cat /tmp/l
Password4
Password3
Somepass4
Password1
(CrackMapExec-VZqQw9ZN) /tmp/CrackMapExec
2020-05-01 22:23:50 192.168.0.102 192.168.74.51
» cme mssql 192.168.74.53 -a normal --local-auth -u sa -p /tmp/l
MSSQL       192.168.74.53   1433   None             [*] MSSQL DB Instances: 1
MSSQL       192.168.74.53   1433   None             Instance 0
MSSQL       192.168.74.53   1433   None             ServerName:OTHERSPN
MSSQL       192.168.74.53   1433   None             InstanceName:MSSQLSERVER
MSSQL       192.168.74.53   1433   None             IsClustered:No
MSSQL       192.168.74.53   1433   None             Version:12.0.5000.0
MSSQL       192.168.74.53   1433   None             tcp:1433
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
```

**Comment by mpgn** [comment]
Try with this binary, first commit miss some connection logic :)
 https://github.com/byt3bl33d3r/CrackMapExec/commit/580018050cb47c9c944251c4f8b4da126135d2e2

**Comment by 0xe7** [comment]
Nope, same result:

```
» ./cme mssql 192.168.74.53 -a normal --local-auth -u sa -p /tmp/l
/root/.shiv/cme_7d78d412e6cc65177f9d9792cde44c3cb1b1b2d3ef2fba15e8b76659d200a11b/site-packages/impacket/smbserver.py:2464: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
/root/.shiv/cme_7d78d412e6cc65177f9d9792cde44c3cb1b1b2d3ef2fba15e8b76659d200a11b/site-packages/impacket/smbserver.py:2500: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
/root/.shiv/cme_7d78d412e6cc65177f9d9792cde44c3cb1b1b2d3ef2fba15e8b76659d200a11b/site-packages/impacket/smbserver.py:2842: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
/root/.shiv/cme_7d78d412e6cc65177f9d9792cde44c3cb1b1b2d3ef2fba15e8b76659d200a11b/site-packages/impacket/smbserver.py:4416: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if credentials_fname is not "":
MSSQL       192.168.74.53   1433   None             [*] MSSQL DB Instances: 1
MSSQL       192.168.74.53   1433   None             Instance 0
MSSQL       192.168.74.53   1433   None             ServerName:OTHERSPN
MSSQL       192.168.74.53   1433   None             InstanceName:MSSQLSERVER
MSSQL       192.168.74.53   1433   None             IsClustered:No
MSSQL       192.168.74.53   1433   None             Version:12.0.5000.0
MSSQL       192.168.74.53   1433   None             tcp:1433
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
```

**Comment by mpgn** [comment]
I suspect this line to break up something
https://github.com/byt3bl33d3r/CrackMapExec/blob/master/cme/protocols/mssql.py#L104

I'm not able to reproduce so you will have to do it by yourself byt cloning and comment this line and check if that works

**Comment by 0xe7** [comment]
I cloned the v5-dev branch and it worked:

```
» cme mssql 192.168.74.53 -a normal --local-auth -u sa -p /tmp/l
MSSQL       192.168.74.53   1433   None             [*] MSSQL DB Instances: 1
MSSQL       192.168.74.53   1433   None             Instance 0
MSSQL       192.168.74.53   1433   None             ServerName:OTHERSPN
MSSQL       192.168.74.53   1433   None             InstanceName:MSSQLSERVER
MSSQL       192.168.74.53   1433   None             IsClustered:No
MSSQL       192.168.74.53   1433   None             Version:12.0.5000.0
MSSQL       192.168.74.53   1433   None             tcp:1433
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [-] ERROR(OTHERSPN): Line 1: Login failed for user 'sa'.
MSSQL       192.168.74.53   1433   None             [+] sa:Somepass4 (ADMIN ACCESS!)
```

**Comment by mpgn** [comment]
Nice @0xe7 , I'm closing the issue :)
