### ISSUE TITLE
Missing required parameter

### ISSUE THREAD

**Issue by vezjak** [byt3bl33d3r/CrackMapExec#376]
**Describe the bug**
"Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/lib/python3/dist-packages/cme/protocols/smb.py", line 110, in __init__
    connection.__init__(self, args, db, host)
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 42, in __init__
    self.proto_flow()
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 74, in proto_flow
    self.login()
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 223, in login
    if self.plaintext_login(self.domain, user, f_pass.strip()): return True
  File "/usr/lib/python3/dist-packages/cme/protocols/smb.py", line 250, in plaintext_login
    self.conn.login(username, password, domain)
  File "/usr/lib/python3/dist-packages/impacket/smbconnection.py", line 267, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/usr/lib/python3/dist-packages/impacket/smb3.py", line 778, in login
    type3, exportedSessionKey = ntlm.getNTLMSSPType3(auth, respToken['ResponseToken'], user, password, domain, lmhash, nthash)
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 631, in getNTLMSSPType3
    ntResponse, lmResponse, sessionBaseKey = computeResponse(ntlmChallenge['flags'], ntlmChallenge['challenge'],
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 39, in computeResponse
    return computeResponseNTLMv2(flags, serverChallenge, clientChallenge, serverName, domain, user, password,
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 902, in computeResponseNTLMv2
    responseKeyNT = NTOWFv2(user, password, domain, nthash)
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 891, in NTOWFv2
    return hmac_md5(theHash, user.upper().encode('utf-16le') + domain.encode('utf-16le'))
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 882, in hmac_md5
    h = hmac.new(key)
  File "/usr/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.8/hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
2020-05-06T10:12:49Z <Greenlet at 0x7f8de20d07b0: smb(Namespace(clear_obfscripts=False, content=False, c, <protocol.database object at 0x7f8de20f2e80>, '10.10.10.184')> failed with TypeError
"

**To Reproduce**
crackmapexec smb 10.10.10.184 -u Nadine -p ./pwd.txt

**Comment by mpgn** [comment]
Closing as you didn't respect the template for bug issue, please you latest version

https://github.com/byt3bl33d3r/CrackMapExec/releases/tag/v5.0.2dev
