### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by TheCoderLife** [byt3bl33d3r/CrackMapExec#385]
## Steps to reproduce

1. apt install crackmapexec
2. ...

## Kali Linux

Installed it already new - but error is still there. Impacket Tools are also new installed.

## Detailed issue explanation

Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==5.0.2.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.2.dev0-py3.8.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.2.dev0-py3.8.egg/cme/thirdparty'

**Comment by mpgn** [comment]
Follow instructions on wiki page https://github.com/byt3bl33d3r/CrackMapExec/wiki

**Comment by Bad3r** [comment]
Hi,
I am experiencing the same issue on Kali Linux 2020.2
```
❯ cme 
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==5.0.2.dev0', 'console_scripts', 'cme')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.2.dev0-py3.8.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.2.dev0-py3.8.egg/cme/thirdparty'
```
I followed the instructions as stated on the wiki page:
```
#~ apt-get install -y libssl-dev libffi-dev python-dev build-essential
#~ git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
#~ cd CrackMapExec
#~ python3 setup.py install
```
