### ISSUE TITLE
ldap [error]

### ISSUE THREAD

**Issue by AdrianInkblack** [byt3bl33d3r/CrackMapExec#398]
cme ldap [ip] -u users.txt -p '' --asreproast output.txt                                                                                                            [0/0]
LDAP        10.10.10.161    389    FOREST           [*] Windows Server 2016 Standard 14393 x64 (name:FOREST) (domain:htb.local) (signing:True) (SMBv1:True)                                                                 
Traceback (most recent call last):                                                                                                                                                           
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run                                   
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/protocols/ldap.py", line 39, in __init__
    connection.__init__(self, args, db, host)
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/connection.py", line 47, in __init__
    self.proto_flow()                                                                         
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/connection.py", line 82, in proto_flow          
    if self.login():                                                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/connection.py", line 251, in login
    if self.plaintext_login(self.domain, user, password): return True                                                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/protocols/ldap.py", line 184, in plaintext_login                                                                                       
    self.ldapConnection = ldap_impacket.LDAPConnection('ldap://%s' % target, self.baseDN, self.kdcHost)                                                                                                                     
  File "/home/intrusionz3r0/.local/lib/python3.8/site-packages/impacket/ldap/ldap.py", line 107, in __init__                                                                                                                
    af, socktype, proto, _, sa = socket.getaddrinfo(targetHost, self._dstPort, 0, socket.SOCK_STREAM)[0]                                                                                                                    
  File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/lib/python3/dist-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)           
  File "/usr/lib/python3/dist-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()                                     
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get             
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get                                      
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__                         
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 371, in g                 
    return f(a)              
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s) 
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()                                                                                                                                                                
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 202, in as_traceback                           
    code = CodeType(                                   
TypeError: an integer is required (got type bytes)                                                            
2020-06-30T18:17:03Z <Greenlet at 0x7f90a8e019d0: ldap(Namespace(admin_count=False, aesKey=None, asreproa, <protocol.database object at 0x7f90a8e9c550>, '10.10.10.161')> failed with TypeError

**Comment by mpgn** [comment]
Can you check again ?
![image](https://user-images.githubusercontent.com/5891788/86175739-28720800-bb24-11ea-9d3b-d8cf4bb3a3bd.png)

**Comment by AdrianInkblack** [comment]
![image](https://user-images.githubusercontent.com/52299647/86195995-cca18200-bb17-11ea-9cf8-1b1d70065379.png)

**Comment by mpgn** [comment]
Mke sure you use latest binary for cme

![image](https://user-images.githubusercontent.com/5891788/86221422-2db36f00-bb85-11ea-880f-62dcaabf62ff.png)

https://github.com/byt3bl33d3r/CrackMapExec/actions/runs/153377014

**Comment by AdrianInkblack** [comment]
![image](https://user-images.githubusercontent.com/52299647/86432591-e250ac00-bcbd-11ea-9874-0123fe33d742.png)
I just had to update my operating system and reinstall Crackmapexec, sorry for the inconvenience and thank you very much

**Comment by mpgn** [comment]
Ok nice, thanks for the update :)
