### ISSUE TITLE
Docker failure due to FileNotFound

### ISSUE THREAD

**Issue by antcoz** [byt3bl33d3r/CrackMapExec#401]
**Describe the bug**
After building the docker file and executing, the following error is returned:

```
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==5.1.0.dev0', 'console_scripts', 'cme')()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/crackmapexec-5.1.0.dev0-py3.8.egg/cme/thirdparty'
```

**To Reproduce**
1. docker run <imagename> cme --help
2. See error

**Expected behavior**
The help is displayed (I think the switch is --help)

**Crackmapexec info**
 - OS: N/A
 - Version of CME: 5.1.0.dev0
 - Installed via Dockerfile

**Comment by mpgn** [comment]
How did you clone the CME repo ?

**Comment by antcoz** [comment]
git clone https://github.com/byt3bl33d3r/CrackMapExec

**Comment by mpgn** [comment]
You need to clone using the flag `recursive`

```
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
```
