### ISSUE TITLE
standalone v5.1.1dev crashes under Windows 

### ISSUE THREAD

**Issue by f0rw4rd** [byt3bl33d3r/CrackMapExec#421]
**Describe the bug**
The windows standalone crashes at launch and it seems like the binary is missing a package or has the wrong version of a package. A fresh install of python 3.9 was used and python 3.7 was tested as well. Can you give me a hint how this could be fixed ? 

**To Reproduce**
```
PS C:\> python cme
Traceback (most recent call last):
  File "C:\cme\_bootstrap\__init__.py", line 74, in import_string
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\cme\__init__.py", line 1, in <module>
    from gevent import monkey
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\cme\_bootstrap\__init__.py", line 74, in import_string
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\cme\__init__.py", line 1, in <module>
    from gevent import monkey
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\cme\__main__.py", line 3, in <module>
  File "C:\cme\_bootstrap\__init__.py", line 233, in bootstrap
  File "C:\cme\_bootstrap\__init__.py", line 79, in import_string
  File "C:\cme\_bootstrap\__init__.py", line 79, in import_string
  File "C:\cme\_bootstrap\__init__.py", line 57, in import_string
  File "C:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\cme\__init__.py", line 1, in <module>
    from gevent import monkey
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\thomas\.shiv\cme_681ca73c0310919c4e78f5c374c18d13f76fc5728e7e7433bb624b0ad2ef3f42\site-packages\gevent\_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'
```

**Expected behavior**
To start without a crash or the packages and versions needed to run the windows standalone binary. 

**Screenshots**
N/A, see log

**Crackmapexec info**
 - OS: Windows 10
 - Version of CME: v5.1.1dev
 - Latest windows standalone  

**Additional context**

Python Version
```
PS C:\> python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
```

Installed python packages: 
```
PS C:\> pip list
Package    Version
---------- -------
pip        20.2.3
setuptools 49.2.1
```

**Comment by mpgn** [comment]
Hello,

The binary is compiled for python3.8, try with 3.8 first :)
