### ISSUE TITLE
No module named 'helpers' Error after Pipx Install

### ISSUE THREAD

**Issue by st1ckyb1ts** [byt3bl33d3r/CrackMapExec#429]
Receiving the below error when trying to run crackmapexec after installing via pipx on 18.04.1-Ubuntu : 
Traceback (most recent call last):
  File "/home/threathunt1/.local/bin/cme", line 5, in <module>
    from cme.crackmapexec import main
  File "/home/threathunt1/.local/pipx/venvs/crackmapexec/lib/python3.6/site-packages/cme/crackmapexec.py", line 10, in <module>
    from cme.connector import connector
  File "/home/threathunt1/.local/pipx/venvs/crackmapexec/lib/python3.6/site-packages/cme/connector.py", line 6, in <module>
    from cme.connection import Connection
  File "/home/threathunt1/.local/pipx/venvs/crackmapexec/lib/python3.6/site-packages/cme/connection.py", line 3, in <module>
    from helpers import highlight
ModuleNotFoundError: No module named 'helpers'

**Comment by mpgn** [comment]
Please put more details and follow the tutorial to install CrackMapExec https://app.gitbook.com/@mpgn/s/crackmapexec-cme/getting-started/installation/installation-on-unix

Closing until more update

**Comment by mpgn** [comment]
Also, you need to use the python v3.8
