### ISSUE TITLE
Try `python3 ./cme`

### ISSUE THREAD

**Issue by Ibrahimous** [byt3bl33d3r/CrackMapExec#438]
Try `python3 ./cme`

_Originally posted by @mpgn in https://github.com/byt3bl33d3r/CrackMapExec/issues/390#issuecomment-646784620_

Got:
Traceback (most recent call last):
  File "./cme/_bootstrap/__init__.py", line 74, in import_string
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/cme/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cme/_bootstrap/__init__.py", line 74, in import_string
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/cme/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./cme/__main__.py", line 3, in <module>
  File "./cme/_bootstrap/__init__.py", line 233, in bootstrap
  File "./cme/_bootstrap/__init__.py", line 79, in import_string
  File "./cme/_bootstrap/__init__.py", line 79, in import_string
  File "./cme/_bootstrap/__init__.py", line 57, in import_string
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/cme/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/ubuntu/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

**Comment by mpgn** [comment]
The binary are compiled with python3.8, install python3.8 and try to exec the binary again :)

**Comment by 4elta** [comment]
> The binary is compiled with python3.8, install python3.8 and try to exec the binary again :)

unfortunately, that doesn't fix the issue; at least not for me.

```
$ python3 -V
Python 3.9.1rc1
$ cme --help                                                                                                                                 
Traceback (most recent call last):                                                                                                           
  File "/home/user/bin/cme/_bootstrap/__init__.py", line 74, in import_string                                                                
  File "/home/user/.shiv/cme_c02f19e8494330cae71f62f5510cef5dac8ec2460e9568c5338a49be2449c683/site-packages/cme/__init__.py", line 1, in <mod
ule>                                                                                                                                         
    from gevent import monkey                                                                                                                
  File "/home/user/.shiv/cme_c02f19e8494330cae71f62f5510cef5dac8ec2460e9568c5338a49be2449c683/site-packages/gevent/__init__.py", line 86, in 
<module>                                                                                                                                     
    from gevent._hub_local import get_hub                                                                                                    
  File "/home/user/.shiv/cme_c02f19e8494330cae71f62f5510cef5dac8ec2460e9568c5338a49be2449c683/site-packages/gevent/_hub_local.py", line 101, 
in <module>                                                                                                                                  
    import_c_accel(globals(), 'gevent.__hub_local')                                                                                          
  File "/home/user/.shiv/cme_c02f19e8494330cae71f62f5510cef5dac8ec2460e9568c5338a49be2449c683/site-packages/gevent/_util.py", line 115, in im
port_c_accel                                                                                                                                 
    mod = importlib.import_module(cname)                                                                                                     
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module                                                                
    return _bootstrap._gcd_import(name[level:], package, level)                                                                              
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'                                                                            

<clipped>
```

... or did you mean one has to use Python 3.8 **exact** (compared to *at least*)?
but that can't be it, or does it?

**Comment by DrRek** [comment]
any fix regarding this one?

**Comment by kpomeroy1979** [comment]
I am encountering the same issue. I have Python3.8 installed in /usr/local/opt/Python3.8/bin and when I try to use Python3.8 with the latest Ubuntu binaries I get the following issue

/usr/local/opt/python-3.8.0/bin/python3.8 ./cme
Traceback (most recent call last):
  File "./cme/_bootstrap/__init__.py", line 74, in import_string
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/cme/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/local/opt/python-3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cme/_bootstrap/__init__.py", line 74, in import_string
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/cme/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/local/opt/python-3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/python-3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python-3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./cme/__main__.py", line 3, in <module>
  File "./cme/_bootstrap/__init__.py", line 233, in bootstrap
  File "./cme/_bootstrap/__init__.py", line 79, in import_string
  File "./cme/_bootstrap/__init__.py", line 79, in import_string
  File "./cme/_bootstrap/__init__.py", line 57, in import_string
  File "/usr/local/opt/python-3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/cme/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/root/.shiv/cme_e41a85cab985f88d51c428f4c4336972a223c722d2c45c2aaefeefa03f421c5a/site-packages/gevent/_util.py", line 115, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/local/opt/python-3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'**
