### ISSUE TITLE
PYTHON3 - OS.SYSTEM("crackmapexec...") COMMAND = EOFERROR

### ISSUE THREAD

**Issue by BroadbentT** [byt3bl33d3r/CrackMapExec#442]
![1](https://user-images.githubusercontent.com/44728186/102280467-1abf0c00-3f25-11eb-84e4-09c4755d56aa.png)

When running crackmapexec commands from python3 using os.system("") - the last command that I run always returns an EoF error. 

No matter what order I put them in, ie. winrm/smb or smb/winrm or how many (1 to 5 commands in a row test), the last command always errors out with an EOFErrorr at the next function call.

The prompt() command shown above is not the issue as it works for all other function calls within my program (https://github.com/BroadbentT/ROGUE-AGENT), and I have put it before the crackmapexec commands and it works!

Its as if the crackmapexec command does not terminate properly when returning to the python coding ?

Kind regards Tez

**Comment by BroadbentT** [comment]
Some more data - I add try on error code - TypeError: can only concatenate str (not "EOFError") to str.
Not sure if it helps ?

Press ENTER to continue...Traceback (most recent call last):
  File "/root/Documents/ROGUE-AGENT/rogue-agent.py", line 2551, in <module>
    null = input("\nPress ENTER to continue...")
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Documents/ROGUE-AGENT/rogue-agent.py", line 2553, in <module>
    print("[!] Crackmap is generating this error: " + e + "...")
TypeError: can only concatenate str (not "EOFError") to str

**Comment by Marshall-Hallenbeck** [comment]
Is this still an issue? I'm not sure this is a problem with CME.
