### ISSUE TITLE
Create the logs folder if it does not exist

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#46]
Hello @byt3bl33d3r,

Currently the script crashes if the `logs` folder does not exist: would you mind to create it (`os.makedirs()`) if it can't be found ?

```
$ crackmapexec.exe 192.168.11.129
Traceback (most recent call last):
  File "<string>", line 169, in <module>
  File "core\logger.py", line 27, in setup_logger
  File "C:\Python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '\\logs\\192.168.11.129_2015-11-27.log'
crackmapexec returned -1
```

Cheers.

**Comment by maaaaz** [comment]
FYI, I proposed it in the PR #52

**Comment by byt3bl33d3r** [comment]
@maaaaz CrackMapExec was designed to be run from the same directory as the main script, if not a lot of stuff will break. Might remove the code that does this in the PR.

**Comment by maaaaz** [comment]
No problem !
