### ISSUE TITLE
Help understanding CME + Defender behavior in Windows

### ISSUE THREAD

**Issue by braimee** [byt3bl33d3r/CrackMapExec#479]
## Steps to reproduce

1. Install Python 3.8.7 - choosing to "Install Now" with default options, and ticking the box for "Add Python 3.8 to PATH.  At the end of the install I choose the "Disable path length limit."  

2. Download CME binary (it doesn't look like the [newest release](https://github.com/byt3bl33d3r/CrackMapExec/releases/tag/v5.1.7dev) has Win binaries so I grabbed [this one](https://github.com/byt3bl33d3r/CrackMapExec/releases/tag/v5.1.1dev) and unzip it.

3. Run `python cme` - get this:

````
C:\Users\Public\pentest-tools>python cme
Traceback (most recent call last):
  File "C:\Users\ptadmin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ptadmin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "cme\__main__.py", line 3, in <module>
  File "cme\_bootstrap\__init__.py", line 233, in bootstrap
  File "cme\_bootstrap\__init__.py", line 57, in import_string
  File "C:\Users\ptadmin\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
OSError: [Errno 22] Invalid argument: 'C:\\Users\\ptadmin\\.shiv\\cme_51b7721208fc3d0af7e301aa9a56e1da0a38e9ec5bc08bfe8cc9ba14853ac5d1\\site-packages\\cme\\crackmapexec.py'
````
4.  Notice that defender is going freakin' nuts quarantining stuff in `c:\users\ptadmin\.shiv`

5.  Disable Defender.

6.  Delete `c:\users\ptadmin\.shiv`

7.  Run `python cme` again - this time things look more encouraging:

````
C:\Users\Public\pentest-tools>python cme
[*] First time use detected
[*] Creating home directory structure
[*] Creating default workspace
[*] Initializing LDAP protocol database
[*] Initializing MSSQL protocol database
[*] Initializing SMB protocol database
[*] Initializing SSH protocol database
[*] Initializing WINRM protocol database
[*] Copying default configuration file
[*] Generating SSL certificate
[-] OpenSSL command line utility is not installed, could not generate certificate, using default certificate
C:\Users\ptadmin\.shiv\cme_51b7721208fc3d0af7e301aa9a56e1da0a38e9ec5bc08bfe8cc9ba14853ac5d1\site-packages\impacket\smbserver.py:2464: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
C:\Users\ptadmin\.shiv\cme_51b7721208fc3d0af7e301aa9a56e1da0a38e9ec5bc08bfe8cc9ba14853ac5d1\site-packages\impacket\smbserver.py:2500: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
C:\Users\ptadmin\.shiv\cme_51b7721208fc3d0af7e301aa9a56e1da0a38e9ec5bc08bfe8cc9ba14853ac5d1\site-packages\impacket\smbserver.py:2842: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
C:\Users\ptadmin\.shiv\cme_51b7721208fc3d0af7e301aa9a56e1da0a38e9ec5bc08bfe8cc9ba14853ac5d1\site-packages\impacket\smbserver.py:4416: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if credentials_fname is not "":
usage: cme [-h] [-t THREADS] [--timeout TIMEOUT] [--jitter INTERVAL] [--darrell] [--verbose] {ldap,mssql,smb,ssh,winrm} ...
````

## Command string used
`python cme`

## CME Version (cme --version)
5.1.1dev

## OS
Windows 10 with latest patches.

## Target OS
None right now.

## Detailed issue explanation
In looking at the steps above, I'm curious is this is the expected behavior or if I've got something wonky in my Python/Windows setup?  I'm a Python newb but my understanding of "shiv" is it allows for self-extracting Python apps?  Do I as the end-user have control of where this `.shiv` folder is created?  If not I can just put a folder exception for Win Defender and be done with it.

**Comment by mpgn** [comment]
Hello,

Put the path .shiv as an exception :)

**Comment by braimee** [comment]
Will do thank you kindly! :D

**Comment by PartyStarterBob** [comment]
Any way to make it more portable by creating the .shiv directory next to the cme binary?
