### ISSUE TITLE
ModuleNotFoundError: No module named 'termcolor' after compiling

### ISSUE THREAD

**Issue by botti007** [byt3bl33d3r/CrackMapExec#482]
After compiling using 
Pyinstall --onefile crack....spec 
when i run crackmapexec.exe  an error appear: anyone could help ?
Traceback (most recent call last):
  File "crackmapexec.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "logger.py", line 5, in <module>
ModuleNotFoundError: No module named 'termcolor'
[12400] Failed to execute script 'crackmapexec' due to unhandled exception!

**Comment by mpgn** [comment]
Should be good with `pip3 install -r requirement` or using `poetry update`
