### ISSUE TITLE
Still some encoding issues

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#51]
@byt3bl33d3r,

It seems that utf-8 is pretty well handled throught the code, except for parameters passed on the command line (login/password, share name stuff etc.):
* In the following example I do have a valid french `àlolé` user :) :
```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec_fork# python crackmapexec.py 192.168.11.136 -u àlolé -p yoloswag1!
11-29-2015 14:42:54 [*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:ADYOLO)
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/mnt/hgfs/Partage/CrackMapExec_fork/core/maingreenlet.py", line 65, in connect
    smb = smart_login(host, smb, domain)
  File "/mnt/hgfs/Partage/CrackMapExec_fork/core/smartlogin.py", line 173, in smart_login
    print_succ(u"{}:{} Login successful {}\\{}:{}".format(host, settings.args.port, domain, user, passwd))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
<Greenlet at 0xb6820accL: connect('192.168.11.136')> failed with UnicodeDecodeError
```

* In the following example I try to list the valid `àéyoloshare` share:
```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec_fork# python crackmapexec.py 192.168.11.136 -u administrator -p test123! --shares --list àéyoloshare
11-29-2015 14:48:24 [*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:ADYOLO)
11-29-2015 14:48:24 [+] 192.168.11.136:445 Login successful ADYOLO\administrator:test123!
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/mnt/hgfs/Partage/CrackMapExec_fork/core/maingreenlet.py", line 78, in connect
    rfs.list()
  File "/mnt/hgfs/Partage/CrackMapExec_fork/core/remotefilesystem.py", line 71, in list
    dir_list = self.__smbconnection.listPath(settings.args.share, path)
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/impacket/smbconnection.py", line 347, in listPath
    return self._SMBConnection.list_path(shareName, path, password)
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/impacket/smb3.py", line 1372, in listPath
    fileId = self.create(treeId, ntpath.dirname(path), FILE_READ_ATTRIBUTES | FILE_READ_DATA ,FILE_SHARE_READ | FILE_SHARE_WRITE |FILE_SHARE_DELETE, FILE_DIRECTORY_FILE | FILE_SYNCHRONOUS_IO_NONALERT, FILE_OPEN, 0)
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/impacket/smb3.py", line 915, in create
    smb2Create['Buffer']               = fileName.encode('utf-16le')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
<Greenlet at 0xb6807accL: connect('192.168.11.136')> failed with UnicodeDecodeError
```

For the first bug I managed to fix it with `user.decode('utf-8')` so I guess you would need to UTF-8 decode each passed argument:
```
print_succ(u"{}:{} Login successful {}\\{}:{}".format(host, settings.args.port, domain, user.decode('utf-8'), passwd))
```
```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec_fork# python crackmapexec.py 192.168.11.136 -u àlolé -p yoloswag1!
11-29-2015 14:59:17 [*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:ADYOLO)
11-29-2015 14:59:17 [+] 192.168.11.136:445 Login successful ADYOLO\àlolé:yoloswag1!
```

The encoding pain is surely close to its end.

EDIT: following [that link](http://stackoverflow.com/questions/22947181/dont-argparse-read-unicode-from-commandline), maybe that simple fix should be OK:
```
parser.add_argument("-u", metavar="USERNAME", dest='user', type=lambda s: unicode(s, 'utf8'), default=None, help="Username(s) or file containing usernames")
```
EDIT2: the error disappear but now a wrong username value is passed to the connection and fails. So UTF-8 decoding should only be done for printing.

Cheers.

**Comment by byt3bl33d3r** [comment]
@maaaaz yup, it should be converted to unicode only when printing, I'll take care of this today. Thanks!

**Comment by byt3bl33d3r** [comment]
@maaaaz this should be fixed, if not comment below

**Comment by maaaaz** [comment]
I confirm this is fixed.
Thanks!

**Comment by maaaaz** [comment]
But as I'm reviewing the `Service Interaction` module I can experience the same errors for service names, display etc. : 
```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec# python ../CrackMapExec_fork/crackmapexec.py 192.168.11.136 -u administrator -p <password>  --service create --name àloléservice --display àloléservice --bin-path "C:\àloléservice.exe"
12-20-2015 17:02:44 [*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:ADYOLO)
12-20-2015 17:02:44 [+] 192.168.11.136:445 Login successful ADYOLO\administrator:test124!
CRITICAL:root:'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

I fixed these errors with the PR https://github.com/byt3bl33d3r/CrackMapExec/pull/62
