### ISSUE TITLE
impacket installation errors

### ISSUE THREAD

**Issue by Slad3G** [byt3bl33d3r/CrackMapExec#54]
Great work on a great tool! On my fresh Kali 2.0 install I get the following when trying to run
**"pip install -r requirements.txt"**

I have attempted to install in a venv and normally.
```
Downloading/unpacking git+git://github.com/CoreSecurity/impacket (from -r requirements.txt (line 1))
  Cloning git://github.com/CoreSecurity/impacket to /tmp/pip-bxbV3L-build
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

  Complete output from command /usr/bin/git clone -q git://github.com/CoreSecurity/impacket /tmp/pip-bxbV3L-build:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git clone -q git://github.com/CoreSecurity/impacket /tmp/pip-bxbV3L-build failed with error code 128 in None
Storing debug log for failure in /root/.pip/pip.log

**From pip.log:**

Cloning git://github.com/CoreSecurity/impacket to /tmp/pip-bxbV3L-build
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q git://github.com/CoreSecurity/impacket /tmp/pip-bxbV3L-build
  Complete output from command /usr/bin/git clone -q git://github.com/CoreSecurity/impacket /tmp/pip-bxbV3L-build:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git clone -q git://github.com/CoreSecurity/impacket /tmp/pip-bxbV3L-build failed with error code 128 in None
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1361, in unpack_url
    unpack_vcs_link(link, loc, only_download)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 344, in unpack_vcs_link
    vcs_backend.unpack(location)
  File "/usr/lib/python2.7/dist-packages/pip/vcs/__init__.py", line 240, in unpack
    self.obtain(location)
  File "/usr/lib/python2.7/dist-packages/pip/vcs/git.py", line 111, in obtain
    call_subprocess([self.cmd, 'clone', '-q', url, dest])
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/git clone -q git://github.com/CoreSecurity/impacket /tmp/pip-bxbV3L-build failed with error code 128 in None
```
Any help would be greatly appreciated.

**Comment by byt3bl33d3r** [comment]
@Slad3G Take a look at the error message, you appeared to have connectivity problems when downloading the dependencies
