### ISSUE TITLE
Nothing work is crashing

### ISSUE THREAD

**Issue by anasbousselham** [byt3bl33d3r/CrackMapExec#556]
I have this error after updating my Kali `Linux kali 5.16.0-kali5-amd64`
My command :
`crackmapexec`

`Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 114, in main
    args = gen_cli_args()
  File "/usr/lib/python3/dist-packages/cme/cli.py", line 71, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/usr/lib/python3/dist-packages/cme/loaders/protocol_loader.py", line 12, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/cme/protocols/ssh.py", line 6, in <module>
    from paramiko.ssh_exception import AuthenticationException, NoValidConnectionsError, SSHException
ImportError: cannot import name 'NoValidConnectionsError' from 'paramiko.ssh_exception' (/home/users/.local/lib/python3.9/site-packages/paramiko/ssh_exception.py)`

**Comment by mnemonic-re** [comment]
Same here. I just did update\upgrade yesterday and crackmapexec broke. Kali 5.15.0-kali3-amd64
Didn't update the kernel yet even.

Just running crackmapexec gives error same as OPs.

**Comment by mllamazares** [comment]
Same here. Any fix to this issue?

**Comment by M0rn1ngst4rr** [comment]
i deinstalled the preinstalled version on kali and installed it via Python package.
worked for me!

**Comment by mpgn** [comment]
closing
