### ISSUE TITLE
Unable to hash spray with username file & nltlm hash files

### ISSUE THREAD

**Issue by kaze-nomamani** [byt3bl33d3r/CrackMapExec#571]
**Describe the bug**
Latest cme can not spray NTLM hash

**To Reproduce**
1: Create username list and ntlm hash list
2: NTLM hash spray with cme

./cme smb ip-u username-list -H ntlm-list

 **error log**

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/pentest/./cme/__main__.py", line 3, in <module>
  File "/home/kali/pentest/./cme/_bootstrap/__init__.py", line 247, in bootstrap
  File "/home/kali/pentest/./cme/_bootstrap/__init__.py", line 38, in run
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/crackmapexec.py", line 254, in main
    asyncio.run(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/crackmapexec.py", line 102, in start_threadpool
    await asyncio.gather(*jobs)
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/crackmapexec.py", line 68, in run_protocol
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/protocols/smb.py", line 125, in __init__
    connection.__init__(self, args, db, host)
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/connection.py", line 62, in __init__
    self.proto_flow()
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/connection.py", line 98, in proto_flow
    if self.login() or (self.username == '' and self.password == ''):
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/connection.py", line 211, in login
    if self.hash_login(self.domain, usr.strip(), f_hash.strip()): return True
  File "/home/kali/.shiv/cme_07092b96173e355ff627274451b8bc2652f1e95de5d91a29675c59dea64de19a/site-packages/cme/protocols/smb.py", line 401, in hash_login
    lmhash, nthash = ntlm_hash.split(':')
ValueError: too many values to unpack (expected 2)

**Crackmapexec info**
 - OS: kali
 - Version of CME: 5.2.2

**Comment by kaze-nomamani** [comment]
Just making long hash format
