### ISSUE TITLE
Mimikatz fail

### ISSUE THREAD

**Issue by juushya** [byt3bl33d3r/CrackMapExec#83]
Using latest crackmapexec.py version.
Target box - Windows 2000.
```
# python crackmapexec.py 192.168.1.10 -d WORKGROUP -u Administrator -p password  —mimikatz  
02-11-2016 16:06:05 SMB 192.168.1.10:445 box1       [*] Windows 5.0 (name:box1) (domain:WORKGROUP)
02-11-2016 16:06:07 SMB 192.168.1.10:445 box1       [+] Login successful WORKGROUP\Administrator:password
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/user/CrackMapExec/core/greenlets.py", line 267, in main_greenlet
    ntlm_hash)
  File "/home/user/CrackMapExec/core/executor.py", line 30, in __init__
    wmi_exec.run(host, connection)
  File "/home/user/CrackMapExec/core/scripts/wmiexec.py", line 68, in run
    iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1053, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1847, in RemoteCreateInstance
    if strBindings[0] == '\x00' and strBindings[1] == '\x00':
IndexError: string index out of range
<Greenlet at 0x99545ec: main_greenlet('192.168.1.10')> failed with IndexError

```

**Comment by byt3bl33d3r** [comment]
@juushya sooo I'm guessing you installed powershell on windows 2000? try appending ```--verbose``` to the command and paste the output
