### ISSUE TITLE
CME wants to write in the database but seems to forget to create the db structure

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#93]
Hello @byt3bl33d3r,

I just updated to 3.0 and facing that error upon the first command launched :) :
```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec# python crackmapexec.py 192.168.11.144
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/mnt/hgfs/Partage/CrackMapExec/core/connector.py", line 49, in connector
    db.add_host(remote_ip, servername, domain, serveros)
  File "/mnt/hgfs/Partage/CrackMapExec/core/database.py", line 12, in add_host
    cur.execute('SELECT * FROM hosts WHERE ip LIKE ?', [ip])
OperationalError: no such table: hosts
<Greenlet at 0xb663d84cL: connector('192.168.11.144', Namespace(command=None, cred_id=None, depth=10, do, <core.database.CMEDatabase instance at 0xb660ce4c>, None, None, None)> failed with OperationalError

04-03-2016 11:08:05 [*] KTHXBYE!
```
The error is pretty obvious, the table `hosts` does not exist and CME tries to add something into it.

Cheers.

**Comment by maaaaz** [comment]
Oops, forget that. I just saw the `setup/setup_database.py` script.
But to be fair this installation should be done at first launch by CME :)

**Comment by maaaaz** [comment]
Aah, a first unicode error:

```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec# python crackmapexec.py 192.168.11.144 -u alolé -p yoloswag1!
04-03-2016 11:39:29 CME          192.168.11.144:445 DC01            [*] Windows 6.3 Build 9600 (name:DC01) (domain:ADYOLO)
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/mnt/hgfs/Partage/CrackMapExec/core/connector.py", line 101, in connector
    connection = Connection(args, db, target, servername, domain, conn, logger, cmeserver)
  File "/mnt/hgfs/Partage/CrackMapExec/core/connection.py", line 26, in __init__
    self.login()
  File "/mnt/hgfs/Partage/CrackMapExec/core/connection.py", line 174, in login
    if self.plaintext_login(user, password): return
  File "/mnt/hgfs/Partage/CrackMapExec/core/connection.py", line 95, in plaintext_login
    highlight('(Pwn3d!)') if self.admin_privs else '')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
<Greenlet at 0xb662784cL: connector('192.168.11.144', Namespace(command=None, cred_id=None, depth=10, do, <core.database.CMEDatabase instance at 0xb65f6d4c>, None, None, None)> failed with UnicodeDecodeError
```

**Comment by maaaaz** [comment]
A second one:
```
(venvcrackmapexec)root@kali:~/Partage/CrackMapExec# python crackmapexec.py 192.168.11.144 -u administrator2 -p <passwd> --share àéyoloshare --spider .
04-03-2016 11:44:34 CME          192.168.11.144:445 DC01            [*] Windows 6.3 Build 9600 (name:DC01) (domain:ADYOLO)
04-03-2016 11:44:34 CME          192.168.11.144:445 DC01            [+] ADYOLO\administrator2:<passwd> (Pwn3d!)
04-03-2016 11:44:34 CME          192.168.11.144:445 DC01            [*] Started spidering
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/mnt/hgfs/Partage/CrackMapExec/core/connector.py", line 170, in connector
    spider.spider(args.spider, args.depth)
  File "/mnt/hgfs/Partage/CrackMapExec/core/spider/smbspider.py", line 33, in spider
    filelist = self.smbconnection.listPath(self.args.share, subfolder)
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/impacket/smbconnection.py", line 347, in listPath
    return self._SMBConnection.list_path(shareName, path, password)
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/impacket/smb3.py", line 1367, in listPath
    treeId = self.connectTree(shareName)
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/impacket/smb3.py", line 804, in connectTree
    treeConnect['Buffer']     = path.encode('utf-16le')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
<Greenlet at 0xb661f84cL: connector('192.168.11.144', Namespace(command=None, cred_id=None, depth=10, do, <core.database.CMEDatabase instance at 0xb65edc8c>, None, None, None)> failed with UnicodeDecodeError

04-03-2016 11:44:34 [*] KTHXBYE!
```

**Comment by byt3bl33d3r** [comment]
Will look into the unicode errors.
Spidering seems to work on my end, whats the exact command you're using?

Also setting up the database automatically would complicate things and would make the code uglier in the main ```crackmapexec.py``` script.

**Comment by byt3bl33d3r** [comment]
@maaaaz just fixed the error handling when db isn't created prior to running the script

**Comment by maaaaz** [comment]
Well as I just realize: why the provided database file cannot already be structured ?
I mean, the setup script does not need to be run by the user, the database file `cme.db` could already be structured with its tables created.

**Comment by byt3bl33d3r** [comment]
@maaaaz cause of git. If I remove the file from the .gitignore list I would have to specifically not add it to every commit (which is just more useless typing)

**Comment by byt3bl33d3r** [comment]
This should be fixed in https://github.com/byt3bl33d3r/CrackMapExec/commit/84dfa1d8391c5da1d985c9a810c46952f644feb8
