### ISSUE TITLE
Error installing Kali 2.0

### ISSUE THREAD

**Issue by mehranexpert** [byt3bl33d3r/CrackMapExec#99]
```
(CME)root@kali:~/Desktop/CrackMapExec/setup# ./setup_database.py 
[*] Database setup completed!
(CME)root@kali:~/Desktop/CrackMapExec/setup# 
(CME)root@kali:~/Desktop/CrackMapExec/setup# cd ..
(CME)root@kali:~/Desktop/CrackMapExec# python crackmapexec.py 
Traceback (most recent call last):
  File "crackmapexec.py", line 9, in <module>
    from core.connector import connector
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/Desktop/CrackMapExec/core/connector.py", line 3, in <module>
    from impacket import tds
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/impacket/tds.py", line 36, in <module>
    import OpenSSL
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
(CME)root@kali:~/Desktop/CrackMapExec# 

```

**Comment by byt3bl33d3r** [comment]
@mehranexpert I'm giving in to peer pressure and will be cranking out install scripts in a few. Hang tight

**Comment by byt3bl33d3r** [comment]
Just pushed a install script for kali, run that and you should be good
